"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadActionPlanPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 12's last step: the rep's plan for the 30 days after certification (daily inputs, one focus skill a week, how they'll keep score with their manager, and what they'll do in a bad week). Coach feedback from /api/action-plan-feedback, then the plan is saved and the certificate page is one click away.
type Area="inputs"|"focus"|"score"|"badWeek";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;dayOne:string;oneChange:string};
type Draft=Record<Area,string>;
const EMPTY:Draft={inputs:"",focus:"",score:"",badWeek:""};
const VERDICT={ready:{label:"Ready to go",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{area:Area;kicker:string;title:string;hint:string;placeholder:string}[]=[
 {area:"inputs",kicker:"DAILY INPUTS",title:"What will you do every day?",hint:"Numbers for the things you control: dials, conversations, call blocks and when they happen. Track appointments too, as a number to learn from, not the goal.",placeholder:"e.g. Two call blocks a day, 9:00–10:30 and 2:00–3:30. 60 dials and at least 8 conversations a day. I’ll track appointments booked each week to see what’s working, not to judge the day."},
 {area:"focus",kicker:"ONE SKILL A WEEK",title:"What will you focus on each week?",hint:"One skill from the course for each of your first four weeks, starting with your weakest. How will you review your calls against it?",placeholder:"e.g. Week 1: the front desk, since I keep getting stuck there. Week 2: discovery that follows the answer. Week 3: “we’re happy.” Week 4: asking for a specific time. Every Friday I’ll listen back to three calls and score just that week’s skill."},
 {area:"score",kicker:"KEEPING SCORE",title:"How will you track it, and who will you review it with?",hint:"Where and when you’ll write your numbers down, and a regular check-in with your manager.",placeholder:"e.g. I’ll log dials, conversations and appointments in my tracker at the end of each block. Every Monday at 8:45 I’ll go over the week’s numbers and my focus skill with my manager for fifteen minutes."},
 {area:"badWeek",kicker:"THE BAD WEEK",title:"What will you do when a week goes badly?",hint:"Decide now, while you’re calm: the first small step you’ll take, who you’ll talk to, and what you’ll reread.",placeholder:"e.g. I’ll explain it in a way I can fix (“my openers ran long,” not “I’m bad at this”), check whether I did my blocks, and pick one thing to change. First step: one call block the next morning, not a whole day. I’ll tell my manager and reread Module 9."},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"inputs",title:"Daily inputs",step:0},{area:"focus",title:"One skill a week",step:1},{area:"score",title:"Keeping score",step:2},{area:"badWeek",title:"The bad week",step:3}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
export default function ActionPlan(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/action-plan-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=!!draft[current.area].trim();
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="certification")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="certification" itemId="action-plan"/><div className="eyebrow">Module 12 · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Your 30-day action plan.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>The last step before your certificate. Plan the month after training: what you&rsquo;ll do every day, one skill to sharpen each week, how you&rsquo;ll keep score with your manager, and what you&rsquo;ll do when a week goes badly.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
<textarea style={{...field,minHeight:160,resize:"vertical"}} maxLength={1500} value={draft[current.area]} onChange={e=>update({[current.area]:e.target.value})} placeholder={current.placeholder}/>
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/quiz/certification">← Back to the Final Exam</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your plan…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="certification" itemId="action-plan"/></div></PreviewGate></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>DAY ONE</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>{feedback.dayOne}</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE TO YOUR PLAN</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the plan as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my plan</button><button className="btn btn-primary" onClick={onSave}>Save my plan →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const saveStatus=useSaveExercise({type:"action-plan",moduleSlug:"certification",itemId:"action-plan",title:"30-day action plan",data:{inputs:draft.inputs,focus:draft.focus,score:draft.score,badWeek:draft.badWeek,dayOne:feedback.dayOne,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadActionPlanPdf({inputs:draft.inputs,focus:draft.focus,score:draft.score,badWeek:draft.badWeek,dayOne:feedback.dayOne,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55,whiteSpace:"pre-line"}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>PLAN SAVED · NEXT 30 DAYS</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>Your 30-day action plan</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("DAILY INPUTS",draft.inputs)}
{row("ONE SKILL A WEEK",draft.focus)}
{row("KEEPING SCORE",draft.score)}
{row("THE BAD WEEK",draft.badWeek)}
{row("DAY ONE",<p style={{fontFamily:"Georgia,serif",fontSize:18,margin:0}}>{feedback.dayOne}</p>)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE TO YOUR PLAN</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Start over</button></div><Link className="btn btn-primary" href="/certificate">See your certificate →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
