"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadOpenerPdf } from "@/lib/pdf";
// Module 3 exercise: the rep builds an opener for a real merchant in four steps, gets coach feedback from /api/opener-feedback, then keeps the opener as a PDF.
type StepKey="merchant"|"reason"|"question"|"opener";
type Area="intro"|"reason"|"question"|"delivery";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;tighterOpener:string;oneChange:string};
type Draft={merchant:string;contact:string;observation:string;reason:string;question:string;opener:string};
const EMPTY:Draft={merchant:"",contact:"",observation:"",reason:"",question:"",opener:""};
const VERDICT={ready:{label:"Ready to dial",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string}[]=[
 {key:"merchant",kicker:"THE MERCHANT",title:"Pick a real merchant.",hint:"Someone on your list this week. Write down one real thing you noticed about them, the kind of thing you'd find in five minutes: a new location, an ownership change, reviews that mention the card reader, an old terminal in photos."},
 {key:"reason",kicker:"YOUR REASON",title:"Turn it into a reason.",hint:"The observation isn't the reason. What it usually means for the merchant is. Say it as something common, not something you're accusing them of."},
 {key:"question",kicker:"CLOSING QUESTION",title:"Write the question you'll end on.",hint:"Specific, about their business, and answerable in about five words. Not a pitch, and not “Do you have a minute?”"},
 {key:"opener",kicker:"THE FULL OPENER",title:"Write it the way you'd say it.",hint:"Your first name and company, your reason, your question. Aim for about ten to fifteen seconds. Say it out loud once before you ask for feedback."},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"intro",title:"Who you are",step:3},{area:"reason",title:"Your reason",step:1},{area:"question",title:"Closing question",step:2},{area:"delivery",title:"Delivery",step:3}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
// Spoken pace of about 150 words a minute.
const words=(t:string)=>t.trim()?t.trim().split(/\s+/).length:0;const seconds=(t:string)=>Math.round(words(t)/2.5);
function filled(d:Draft,key:StepKey){switch(key){case "merchant":return !!(d.merchant.trim()&&d.observation.trim());case "reason":return !!d.reason.trim();case "question":return !!d.question.trim();case "opener":return !!d.opener.trim()}}
export default function OpenerPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/opener-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
const secs=seconds(draft.opener);
return <AppShell active="Practice"><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="opening-the-conversation" itemId="opener"/><div className="eyebrow">Module 3 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Write your opener.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>Build a real opener for a real merchant on your list: who you are, a reason that&apos;s about them, and one easy question. The coach checks it against the lessons, and you keep it for your next call block.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="merchant"&&<div style={{display:"grid",gap:18}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Business and type</span><input style={field} maxLength={1000} value={draft.merchant} onChange={e=>update({merchant:e.target.value})} placeholder="e.g. Rosa's Taqueria, two-location restaurant"/></label><label><span style={labelStyle}>Contact&apos;s first name (if you have it)</span><input style={field} maxLength={1000} value={draft.contact} onChange={e=>update({contact:e.target.value})} placeholder="e.g. Maria"/></label></div><label><span style={labelStyle}>What you noticed</span><textarea style={{...field,minHeight:110,resize:"vertical"}} maxLength={1000} value={draft.observation} onChange={e=>update({observation:e.target.value})} placeholder="One real observation about this business."/></label></div>}
{current.key==="reason"&&<div style={{display:"grid",gap:14}}>{draft.observation.trim()&&<div style={{background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>YOU NOTICED</small><p style={{margin:"6px 0 0",lineHeight:1.55}}>{draft.observation}</p></div>}<textarea style={{...field,minHeight:130,resize:"vertical"}} maxLength={1000} value={draft.reason} onChange={e=>update({reason:e.target.value})} placeholder="e.g. Owners who open a second location often end up running two card systems that don't talk to each other."/></div>}
{current.key==="question"&&<input style={field} maxLength={1000} value={draft.question} onChange={e=>update({question:e.target.value})} placeholder="e.g. Did you keep the same processor for both locations?"/>}
{current.key==="opener"&&<div><textarea style={{...field,minHeight:160,resize:"vertical"}} maxLength={1000} value={draft.opener} onChange={e=>update({opener:e.target.value})} placeholder={`Hi ${draft.contact.trim()||"Maria"}, it's …`}/><p style={{fontSize:13,margin:"8px 0 0",color:secs>18?RED:"var(--muted)"}}>{words(draft.opener)} words · about {secs} seconds out loud{secs>18?". That's long. Aim for 10 to 15.":""}</p></div>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/opening-the-conversation/lessons/ask-for-the-next-30-seconds">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your opener…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="opening-the-conversation" itemId="opener"/></div></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH&apos;S TIGHTER VERSION</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>&ldquo;{feedback.tighterOpener}&rdquo;</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE YOU DIAL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the opener as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my opener</button><button className="btn btn-primary" onClick={onSave}>Save my opener →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const saveStatus=useSaveExercise({type:"opener",moduleSlug:"opening-the-conversation",itemId:"opener",title:`Opener: ${draft.merchant}`,data:{merchant:draft.merchant,contact:draft.contact,observation:draft.observation,reason:draft.reason,question:draft.question,opener:draft.opener,tighterOpener:feedback.tighterOpener,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadOpenerPdf({merchant:draft.merchant,contact:draft.contact,observation:draft.observation,opener:draft.opener,tighterOpener:feedback.tighterOpener,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>OPENER SAVED</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{draft.merchant}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("WHAT YOU NOTICED",draft.observation)}
{row("YOUR OPENER",<p style={{fontFamily:"Georgia,serif",fontSize:19,margin:0}}>&ldquo;{draft.opener}&rdquo;</p>)}
{row("COACH'S TIGHTER VERSION",<p style={{fontFamily:"Georgia,serif",fontSize:19,margin:0}}>&ldquo;{feedback.tighterOpener}&rdquo;</p>)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE THE FIRST DIAL</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p><p style={{margin:"12px 0 0",fontSize:14,color:"var(--muted)",lineHeight:1.55}}>Then say the opener out loud until it sounds like something you&apos;d actually say, not something you&apos;re reading.</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Write another opener</button></div><Link className="btn btn-primary" href="/quiz/opening-the-conversation">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
