"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { module1Quiz as questions, PASS_MARK } from "@/data/quiz"; import { downloadQuizResultsPdf } from "@/lib/reflectionPdf";
const MODULE_TITLE="Understanding Call Reluctance";const MODULE_SLUG="understanding-call-reluctance";const NEXT_MODULE="/courses/preparing-to-make-calls";
const RED="#a3320b";
export default function Quiz(){const [idx,setIdx]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [submitted,setSubmitted]=useState(false);const [picks,setPicks]=useState<number[]>([]);const [finished,setFinished]=useState(false);
const q=questions[idx];const isLast=idx===questions.length-1;
const submit=()=>{if(choice===null)return;setSubmitted(true);setPicks(p=>[...p.slice(0,idx),choice])};
const next=()=>{if(isLast){setFinished(true);window.scrollTo(0,0);return}setIdx(idx+1);setChoice(null);setSubmitted(false)};
const retake=()=>{setIdx(0);setChoice(null);setSubmitted(false);setPicks([]);setFinished(false)};
const progress=finished?100:((idx+(submitted?1:0))/questions.length)*100;
return <AppShell active="Knowledge checks"><div style={{padding:"50px 4vw",maxWidth:850,margin:"auto"}}><div className="eyebrow">Module 1 knowledge check</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"end"}}><h1 className="display" style={{fontSize:38,margin:"14px 0 10px"}}>{finished?"Your results.":"Check your understanding."}</h1>{!finished&&<span style={{fontSize:13,color:"var(--muted)"}}>{idx+1} of {questions.length}</span>}</div><div className="progress" style={{margin:"14px 0 30px"}}><span style={{width:`${progress}%`}}/></div>
{finished?<Results picks={picks} onRetake={retake}/>:<section className="card" style={{padding:34}}><div style={{fontSize:12,fontWeight:900,color:"var(--green)",letterSpacing:".12em"}}>QUESTION {String(idx+1).padStart(2,"0")}</div><h2 style={{fontFamily:"Georgia,serif",fontSize:24,lineHeight:1.4,margin:"16px 0 26px"}}>{q.prompt}</h2><div style={{display:"grid",gap:11}}>{q.choices.map((c,i)=>{const isAnswer=i===q.answer;const isPick=i===choice;const state=!submitted?(isPick?"picked":"idle"):isAnswer?"correct":isPick?"wrong":"idle";const border=state==="correct"?"var(--green)":state==="wrong"?RED:state==="picked"?"var(--green)":"var(--line)";const bg=state==="correct"?"#e3f1e7":state==="wrong"?"#fbe9e2":state==="picked"?"#edf5ef":"white";return <button onClick={()=>!submitted&&setChoice(i)} disabled={submitted} key={c} style={{textAlign:"left",padding:"17px 18px",borderRadius:12,border:`1px solid ${border}`,background:bg,display:"flex",gap:14,cursor:submitted?"default":"pointer",color:"var(--ink)",opacity:submitted&&state==="idle"?.6:1}}><span style={{width:25,height:25,borderRadius:"50%",border:`2px solid ${state==="idle"?"#c7cfca":border}`,background:state==="correct"?"var(--green)":state==="wrong"?RED:"transparent",color:state==="correct"||state==="wrong"?"white":"inherit",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,flex:"0 0 auto"}}>{state==="correct"?"✓":state==="wrong"?"✕":String.fromCharCode(65+i)}</span><span style={{lineHeight:1.5}}>{c}</span></button>})}</div>
{submitted&&<div aria-live="polite" style={{marginTop:22,borderLeft:`5px solid ${choice===q.answer?"var(--green)":RED}`,background:choice===q.answer?"#f2f6e7":"#fdf3ef",padding:"18px 22px"}}><b style={{color:choice===q.answer?"var(--green)":RED}}>{choice===q.answer?"Correct.":`Not quite. The answer is ${String.fromCharCode(65+q.answer)}.`}</b><p style={{margin:"8px 0 10px",lineHeight:1.6,color:"var(--ink)"}}>{q.explanation}</p><Link href={`/courses/${MODULE_SLUG}/lessons/${q.lesson.id}`} style={{fontSize:13,fontWeight:800,color:"var(--green)"}}>Review: {q.lesson.title} →</Link></div>}
<div style={{display:"flex",justifyContent:"flex-end",marginTop:26}}>{submitted?<button className="btn btn-primary" onClick={next}>{isLast?"See results →":"Next question →"}</button>:<button className="btn btn-primary" disabled={choice===null} onClick={submit}>Submit answer →</button>}</div></section>}</div></AppShell>}
function Results({picks,onRetake}:{picks:number[];onRetake:()=>void}){const score=picks.filter((p,i)=>p===questions[i].answer).length;const passed=score>=PASS_MARK;const missed=questions.map((q,i)=>({q,i})).filter(({q,i})=>picks[i]!==q.answer);const [pdfError,setPdfError]=useState("");
const downloadPdf=()=>{setPdfError("");downloadQuizResultsPdf({moduleTitle:MODULE_TITLE,score,total:questions.length,passed,passMark:PASS_MARK,date:new Date(),items:questions.map((q,i)=>({prompt:q.prompt,chosen:q.choices[picks[i]],correct:q.choices[q.answer],isCorrect:picks[i]===q.answer,explanation:q.explanation}))}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
return <div><section className="card" style={{overflow:"hidden"}}><div style={{background:passed?"var(--green)":"var(--ink)",color:"white",padding:"30px 34px",display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,flexWrap:"wrap"}}><div><small style={{color:"var(--lime)",fontWeight:900,letterSpacing:".12em"}}>{passed?"PASSED":"NOT YET PASSED"}</small><div style={{fontFamily:"Georgia,serif",fontSize:46,margin:"6px 0 4px"}}>{score} of {questions.length}</div><span style={{fontSize:13,color:"#c9dbd5"}}>Pass mark: {PASS_MARK} of {questions.length} correct</span></div><p style={{maxWidth:360,margin:0,lineHeight:1.55,color:"#e3ece8"}}>{passed?(score===questions.length?"A perfect score. You can apply every idea in this module, not just recognize it.":"Solid. Review the one you missed, then move on to Module 2."):"Close, but not there yet. Review the lessons below and retake the check. The questions stay the same, so focus on why each answer is right."}</p></div>
<div style={{padding:"10px 34px 28px"}}>{missed.length===0?<p style={{padding:"18px 0 0",color:"var(--muted)"}}>No missed questions.</p>:<><h2 style={{fontFamily:"Georgia,serif",fontSize:22,margin:"20px 0 6px"}}>Review what you missed</h2>{missed.map(({q,i})=><div key={i} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>QUESTION {String(i+1).padStart(2,"0")}</small><p style={{margin:"6px 0 8px",lineHeight:1.5,fontWeight:700}}>{q.prompt}</p><p style={{margin:"0 0 4px",fontSize:14,color:RED}}>Your answer: {q.choices[picks[i]]}</p><p style={{margin:"0 0 10px",fontSize:14,color:"var(--green)"}}>Correct: {q.choices[q.answer]}</p><Link href={`/courses/${MODULE_SLUG}/lessons/${q.lesson.id}`} style={{fontSize:13,fontWeight:800,color:"var(--green)"}}>Review: {q.lesson.title} →</Link></div>)}</>}</div></section>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRetake}>Retake</button></div>{passed?<Link className="btn btn-primary" href={NEXT_MODULE}>Continue to Module 2 →</Link>:<Link className="btn btn-primary" href={`/courses/${MODULE_SLUG}`}>Back to Module 1 →</Link>}</div>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
