"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadFollowUpPlanPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 8 exercise: for one real merchant who said "not right now", the rep writes where things stand, the next follow-up message, the cadence and the stop rule, gets coach feedback (plus an honest closing message) from /api/follow-up-plan-feedback, then keeps the plan as a PDF.
type StepKey="merchant"|"situation"|"message"|"cadence"|"stopRule";
type Area=Exclude<StepKey,"merchant">;
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;lastMessage:string;oneChange:string};
type Draft={vertical:string;merchant:string;situation:string;message:string;cadence:string;stopRule:string};
const EMPTY:Draft={vertical:"",merchant:"",situation:"",message:"",cadence:"",stopRule:""};
const VERTICALS=["Restaurant","Retail","Service business (salon, auto, contractor)","E-commerce","Other"];
const VERDICT={ready:{label:"Ready to send",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string;placeholder:string}[]=[
 {key:"merchant",kicker:"THE MERCHANT",title:"Pick a real merchant who said “not right now.”",hint:"Someone on your list who wasn’t ready, or who went quiet after a good conversation.",placeholder:""},
 {key:"situation",kicker:"WHERE THINGS STAND",title:"What did they say, and why not now?",hint:"Their words, the real reason behind “not now,” and any timing they gave you: a busy season, a contract end date, a new location, a partner who decides.",placeholder:"e.g. Owner Maria said, “We’re slammed until after the holidays, and honestly the fees confuse me.” Contract with current processor ends in March. Her husband does the books."},
 {key:"message",kicker:"THE NEXT FOLLOW-UP",title:"Write the next message you’ll send.",hint:"Open with something they said, give them something useful, and end with one small ask. No “just checking in.”",placeholder:"e.g. Hi Maria, when we spoke in November you mentioned the fees were confusing and your contract ends in March. If you’d like, I can go through one statement and show you exactly what each fee is. Would ten minutes the week of January 8 work?"},
 {key:"cadence",kicker:"THE CADENCE",title:"When, and how, will you follow up after that?",hint:"Follow their timing, mix phone, email and voicemail, and spread contacts out if there’s no set date. Say how you’ll log each one.",placeholder:"e.g. Email Jan 6, call Jan 9 at 3 p.m. (after lunch rush), voicemail pointing to the email if no answer. Then every two weeks until mid-February, before the renewal. Log her words and the next date in the CRM after every contact."},
 {key:"stopRule",kicker:"CLOSING THE FILE",title:"When will you stop, and how?",hint:"What tells you it’s time to stop, how you’ll handle a request to stop, what your last message says, and whether a long-range check-back makes sense.",placeholder:"e.g. If there’s no reply after four useful touches, I’ll send one honest closing note and stop. If she asks me not to call, I’ll mark her do-not-call right away. Reminder for next January if she renews for a year."},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"situation",title:"Where things stand",step:1},{area:"message",title:"Next follow-up message",step:2},{area:"cadence",title:"Cadence",step:3},{area:"stopRule",title:"Closing the file",step:4}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
function filled(d:Draft,key:StepKey){return key==="merchant"?!!(d.vertical&&d.merchant.trim()):!!d[key].trim()}
export default function FollowUpPlanPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/follow-up-plan-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="follow-up")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="follow-up" itemId="follow-up-plan"/><div className="eyebrow">Module 8 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Plan your follow-up.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>For one real merchant who said &ldquo;not right now,&rdquo; plan how you&rsquo;ll stay in touch without chasing: where things stand, the next message you&rsquo;ll send, the cadence after it, and when you&rsquo;ll close the file. The coach checks it against the lessons and drafts an honest closing message for you.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="merchant"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Vertical</span><select style={field} value={draft.vertical} onChange={e=>update({vertical:e.target.value})}><option value="">Choose one…</option>{VERTICALS.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span style={labelStyle}>Business</span><input style={field} maxLength={1500} value={draft.merchant} onChange={e=>update({merchant:e.target.value})} placeholder="e.g. Casa Verde, family restaurant"/></label></div>
:<textarea style={{...field,minHeight:160,resize:"vertical"}} maxLength={1500} value={draft[current.key]} onChange={e=>update({[current.key]:e.target.value})} placeholder={current.placeholder}/>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/follow-up/lessons/close-the-file">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your plan…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="follow-up" itemId="follow-up-plan"/></div></PreviewGate></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>IF THEY STAY QUIET: YOUR LAST MESSAGE</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>&ldquo;{feedback.lastMessage}&rdquo;</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE YOU SEND</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the plan as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my plan</button><button className="btn btn-primary" onClick={onSave}>Save my plan →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const saveStatus=useSaveExercise({type:"follow-up-plan",moduleSlug:"follow-up",itemId:"follow-up-plan",title:`Follow-up plan: ${draft.merchant}`,data:{vertical:draft.vertical,merchant:draft.merchant,situation:draft.situation,message:draft.message,cadence:draft.cadence,stopRule:draft.stopRule,lastMessage:feedback.lastMessage,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadFollowUpPlanPdf({vertical:draft.vertical,merchant:draft.merchant,situation:draft.situation,message:draft.message,cadence:draft.cadence,stopRule:draft.stopRule,lastMessage:feedback.lastMessage,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55,whiteSpace:"pre-line"}}>{body}</div></div>;
const quote=(t:string)=><p style={{fontFamily:"Georgia,serif",fontSize:18,margin:0}}>&ldquo;{t}&rdquo;</p>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>PLAN SAVED · {draft.vertical.toUpperCase()}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{draft.merchant}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("WHERE THINGS STAND",draft.situation)}
{row("NEXT FOLLOW-UP",quote(draft.message))}
{row("CADENCE",draft.cadence)}
{row("CLOSING THE FILE",draft.stopRule)}
{row("IF THEY STAY QUIET",quote(feedback.lastMessage))}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE YOU SEND</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Plan another follow-up</button></div><Link className="btn btn-primary" href="/quiz/follow-up">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
