"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadDiscoveryPlanPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 5 exercise: the rep plans discovery for one real merchant (an opening question with context, an impact question, a likely answer and follow-up, who else decides and the statement), gets coach feedback from /api/discovery-plan-feedback, then keeps the plan as a PDF.
type StepKey="merchant"|"opening"|"impact"|"followUp"|"finish";
type Area="opening"|"impact"|"followUp"|"finish";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;listenFor:string;oneChange:string};
type Draft={vertical:string;merchant:string;opening:string;impact:string;likelyAnswer:string;followUp:string;decision:string;statement:string};
const EMPTY:Draft={vertical:"",merchant:"",opening:"",impact:"",likelyAnswer:"",followUp:"",decision:"",statement:""};
const VERTICALS=["Restaurant","Retail","Service business (salon, auto, contractor)","E-commerce","Other"];
const VERDICT={ready:{label:"Ready to call",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string}[]=[
 {key:"merchant",kicker:"THE MERCHANT",title:"Pick a real merchant to plan for.",hint:"Someone on your list this week. Before you write anything else, look at their website: every setup fact you find there is one less question on the phone."},
 {key:"opening",kicker:"YOUR FIRST QUESTION",title:"One question, with a reason in front of it.",hint:"A short piece of context that shows you know their world, then a single question. Not a stack of three, and not a line from your form."},
 {key:"impact",kicker:"THE IMPACT QUESTION",title:"Ask what the problem costs them.",hint:"Not how they're set up, but what a problem does to their time, money or customers. Ask it honestly, and be ready to accept “it’s actually fine.”"},
 {key:"followUp",kicker:"FOLLOW THE ANSWER",title:"What might they say, and how will you follow it?",hint:"Write something this merchant might realistically say, then the follow-up you’d build from their words: clarify it, size it, or ask what they’ve tried."},
 {key:"finish",kicker:"KNOW WHAT THE APPOINTMENT NEEDS",title:"How will you close out discovery?",hint:"Find out who else weighs in without asking “Are you the decision-maker?”, then get the statement and anything that shapes timing. Then stop digging and book it."},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"opening",title:"First question",step:1},{area:"impact",title:"Impact question",step:2},{area:"followUp",title:"Follow-up",step:3},{area:"finish",title:"Closing out discovery",step:4}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
function filled(d:Draft,key:StepKey){switch(key){case "merchant":return !!(d.vertical&&d.merchant.trim());case "opening":return !!d.opening.trim();case "impact":return !!d.impact.trim();case "followUp":return !!(d.likelyAnswer.trim()&&d.followUp.trim());case "finish":return !!(d.decision.trim()&&d.statement.trim())}}
export default function DiscoveryPlanPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/discovery-plan-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="discovery-questions")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="discovery-questions" itemId="discovery-plan"/><div className="eyebrow">Module 5 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Plan your discovery.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>For one real merchant on your list: the first question you&rsquo;ll ask, the question about what their problem costs them, how you&rsquo;ll follow their answer, and how you&rsquo;ll close out discovery and book the meeting. The coach checks it against the lessons, and you keep the plan for your next call block.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="merchant"&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Vertical</span><select style={field} value={draft.vertical} onChange={e=>update({vertical:e.target.value})}><option value="">Choose one…</option>{VERTICALS.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span style={labelStyle}>Business</span><input style={field} maxLength={1000} value={draft.merchant} onChange={e=>update({merchant:e.target.value})} placeholder="e.g. Ridgeline Heating & Air, three service vans"/></label></div>}
{current.key==="opening"&&<textarea style={{...field,minHeight:120,resize:"vertical"}} maxLength={1000} value={draft.opening} onChange={e=>update({opening:e.target.value})} placeholder="e.g. A lot of contractors we talk to end up chasing invoices after the job’s done. How do your techs usually get paid right now?"/>}
{current.key==="impact"&&<textarea style={{...field,minHeight:120,resize:"vertical"}} maxLength={1000} value={draft.impact} onChange={e=>update({impact:e.target.value})} placeholder="e.g. When an invoice sits for three weeks, what does that do to how you pay your crew and buy materials?"/>}
{current.key==="followUp"&&<div style={{display:"grid",gap:18}}><label><span style={labelStyle}>They might say</span><textarea style={{...field,minHeight:90,resize:"vertical"}} maxLength={1000} value={draft.likelyAnswer} onChange={e=>update({likelyAnswer:e.target.value})} placeholder="e.g. Honestly, collections are a nightmare. My office manager spends half of Friday on the phone."/></label><label><span style={labelStyle}>You follow with</span><textarea style={{...field,minHeight:90,resize:"vertical"}} maxLength={1000} value={draft.followUp} onChange={e=>update({followUp:e.target.value})} placeholder="e.g. Half of Friday, every week? What have you tried so far to speed that up?"/></label></div>}
{current.key==="finish"&&<div style={{display:"grid",gap:18}}><label><span style={labelStyle}>How you&rsquo;ll ask who else weighs in</span><input style={field} maxLength={1000} value={draft.decision} onChange={e=>update({decision:e.target.value})} placeholder="e.g. Besides you, who else would want to weigh in on something like this?"/></label><label><span style={labelStyle}>How you&rsquo;ll ask for the statement and timing</span><textarea style={{...field,minHeight:90,resize:"vertical"}} maxLength={1000} value={draft.statement} onChange={e=>update({statement:e.target.value})} placeholder="e.g. If you can have last month’s processing statement handy, we can show you exactly where the money goes. Anything coming up, like a contract ending or new equipment?"/></label></div>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/discovery-questions/lessons/what-the-appointment-needs">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your plan…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="discovery-questions" itemId="discovery-plan"/></div></PreviewGate></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>LISTEN FOR THESE WORDS</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>{feedback.listenFor}</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the plan as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my plan</button><button className="btn btn-primary" onClick={onSave}>Save my plan →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const saveStatus=useSaveExercise({type:"discovery-plan",moduleSlug:"discovery-questions",itemId:"discovery-plan",title:`Discovery plan: ${draft.merchant}`,data:{vertical:draft.vertical,merchant:draft.merchant,opening:draft.opening,impact:draft.impact,likelyAnswer:draft.likelyAnswer,followUp:draft.followUp,decision:draft.decision,statement:draft.statement,listenFor:feedback.listenFor,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadDiscoveryPlanPdf({vertical:draft.vertical,merchant:draft.merchant,opening:draft.opening,impact:draft.impact,likelyAnswer:draft.likelyAnswer,followUp:draft.followUp,decision:draft.decision,statement:draft.statement,listenFor:feedback.listenFor,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55}}>{body}</div></div>;
const quote=(t:string)=><p style={{fontFamily:"Georgia,serif",fontSize:18,margin:0}}>&ldquo;{t}&rdquo;</p>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>PLAN SAVED · {draft.vertical.toUpperCase()}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{draft.merchant}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("FIRST QUESTION",quote(draft.opening))}
{row("IMPACT QUESTION",quote(draft.impact))}
{row("IF THEY SAY",draft.likelyAnswer)}
{row("YOU FOLLOW WITH",quote(draft.followUp))}
{row("WHO ELSE WEIGHS IN",quote(draft.decision))}
{row("STATEMENT AND TIMING",draft.statement)}
<div style={{margin:"6px 0 0",background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"14px 18px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>LISTEN FOR</small><p style={{fontFamily:"Georgia,serif",fontSize:18,margin:"6px 0 0",lineHeight:1.5}}>{feedback.listenFor}</p></div>
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Plan another call</button></div><Link className="btn btn-primary" href="/quiz/discovery-questions">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
