"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadObjectionPlaybookPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 6 exercise: the rep writes what they'll say to the four common objections for one real merchant, gets coach feedback from /api/objection-playbook-feedback, then keeps the playbook as a PDF.
type StepKey="merchant"|"notInterested"|"happy"|"sendInfo"|"price";
type Area=Exclude<StepKey,"merchant">;
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;exitLine:string;oneChange:string};
type Draft={vertical:string;merchant:string;notInterested:string;happy:string;sendInfo:string;price:string};
const EMPTY:Draft={vertical:"",merchant:"",notInterested:"",happy:"",sendInfo:"",price:""};
const VERTICALS=["Restaurant","Retail","Service business (salon, auto, contractor)","E-commerce","Other"];
const VERDICT={ready:{label:"Ready to call",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string;placeholder:string}[]=[
 {key:"merchant",kicker:"THE MERCHANT",title:"Pick a real merchant to prepare for.",hint:"Someone on your list this week. Your answers should fit their kind of business, not every business.",placeholder:""},
 {key:"notInterested",kicker:"“NOT INTERESTED”",title:"They say it ten seconds in. What do you say?",hint:"Acknowledge what’s true, give your reason in one line, and ask one easy question about their business. No pitch, no pressure.",placeholder:"e.g. That’s fair, you weren’t expecting my call. Before I let you go, when did someone last walk you through your processing statement?"},
 {key:"happy",kicker:"“WE’RE HAPPY WITH WHO WE HAVE”",title:"How do you respond without attacking their processor?",hint:"Agree with them, ask what “happy” covers, and offer a small check-up instead of a switch. Be ready to tell them honestly if they’re in good shape.",placeholder:"e.g. Good, that’s what you want. If you could change one thing about how payments work here, what would it be?"},
 {key:"sendInfo",kicker:"“JUST SEND ME SOME INFORMATION”",title:"How do you narrow it and tie it to a next step?",hint:"Say yes, ask what would make it worth reading, and attach a short, specific follow-up.",placeholder:"e.g. Happy to. So I send something useful, what matters most: what you’re paying, how fast you get funded, or how it works with your POS? I’ll send it today. Could we take ten minutes Thursday to go over it?"},
 {key:"price",kicker:"“WHAT’S YOUR RATE?”",title:"What do you say instead of quoting a number?",hint:"Be straight that a rate without a statement is a guess, offer to work out what they really pay now, and ask what they pay today.",placeholder:"e.g. Honestly, anyone who quotes you a rate without seeing your statement is guessing. What are you paying now? If you’re not sure, I can work out your real rate from one statement."},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"notInterested",title:"“Not interested”",step:1},{area:"happy",title:"“We’re happy”",step:2},{area:"sendInfo",title:"“Send me information”",step:3},{area:"price",title:"“What’s your rate?”",step:4}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
function filled(d:Draft,key:StepKey){return key==="merchant"?!!(d.vertical&&d.merchant.trim()):!!d[key].trim()}
export default function ObjectionPlaybookPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/objection-playbook-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="handling-objections")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="handling-objections" itemId="objection-playbook"/><div className="eyebrow">Module 6 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Build your objection playbook.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>For one real merchant on your list, write what you&rsquo;ll actually say when you hear the four objections that come up most. The coach checks each answer against the lessons, and you keep the playbook next to the phone.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="merchant"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Vertical</span><select style={field} value={draft.vertical} onChange={e=>update({vertical:e.target.value})}><option value="">Choose one…</option>{VERTICALS.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span style={labelStyle}>Business</span><input style={field} maxLength={1000} value={draft.merchant} onChange={e=>update({merchant:e.target.value})} placeholder="e.g. Corner Grind Coffee, one location"/></label></div>
:<textarea style={{...field,minHeight:140,resize:"vertical"}} maxLength={1000} value={draft[current.key]} onChange={e=>update({[current.key]:e.target.value})} placeholder={current.placeholder}/>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/handling-objections/lessons/price-resistance">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your playbook…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="handling-objections" itemId="objection-playbook"/></div></PreviewGate></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>IF THEY SAY NO TWICE</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>&ldquo;{feedback.exitLine}&rdquo;</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any answer to get fresh feedback, or save the playbook as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my playbook</button><button className="btn btn-primary" onClick={onSave}>Save my playbook →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const saveStatus=useSaveExercise({type:"objection-playbook",moduleSlug:"handling-objections",itemId:"objection-playbook",title:`Objection playbook: ${draft.merchant}`,data:{vertical:draft.vertical,merchant:draft.merchant,notInterested:draft.notInterested,happy:draft.happy,sendInfo:draft.sendInfo,price:draft.price,exitLine:feedback.exitLine,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadObjectionPlaybookPdf({vertical:draft.vertical,merchant:draft.merchant,notInterested:draft.notInterested,happy:draft.happy,sendInfo:draft.sendInfo,price:draft.price,exitLine:feedback.exitLine,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,text:string)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><p style={{fontFamily:"Georgia,serif",fontSize:18,margin:"8px 0 0",lineHeight:1.5}}>&ldquo;{text}&rdquo;</p></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>PLAYBOOK SAVED · {draft.vertical.toUpperCase()}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{draft.merchant}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("WHEN THEY SAY “NOT INTERESTED”",draft.notInterested)}
{row("WHEN THEY SAY “WE’RE HAPPY”",draft.happy)}
{row("WHEN THEY SAY “SEND ME INFORMATION”",draft.sendInfo)}
{row("WHEN THEY ASK “WHAT’S YOUR RATE?”",draft.price)}
{row("IF THEY SAY NO TWICE",feedback.exitLine)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Build another playbook</button></div><Link className="btn btn-primary" href="/quiz/handling-objections">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
