"use client"; import Link from "next/link"; import { useEffect, useRef, useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { scenarios, type Scenario } from "@/data/scenarios"; import { CALL_TIMES, MAX_REP_CHARS, MAX_TURNS, type Turn } from "@/lib/roleplay";
// Call simulator: the rep picks a merchant and a time, then types their side of a live call while the AI plays whoever answers and the owner (/api/roleplay). When the call ends, the coach scores the transcript against the five moves (/api/roleplay-feedback) and the call is saved to the journal. It's open practice, not a course item, so it never marks anything complete.
type Outcome="ongoing"|"booked"|"callback"|"ended"|"hung_up";
type Move="intro"|"question"|"steady"|"number"|"time";
type Feedback={summary:string;moves:Record<Move,boolean>;bestLine:string;turningPoint:string;tryInstead:string;oneChange:string};
const MOVES:{move:Move;label:string}[]=[{move:"intro",label:"Who you are and why you’re calling"},{move:"question",label:"A question about their business"},{move:"steady",label:"Steady through the first no"},{move:"number",label:"One number in their terms"},{move:"time",label:"A specific day and time"}];
const OUTCOME:Record<Exclude<Outcome,"ongoing">,{label:string;bg:string;fg:string}>={booked:{label:"Meeting booked",bg:"var(--green)",fg:"white"},callback:{label:"Told when to call back",bg:"var(--lime)",fg:"var(--ink)"},ended:{label:"Call ended, no meeting",bg:"#f3d9c9",fg:"#7a2e0e"},hung_up:{label:"You hung up",bg:"#edf0e9",fg:"var(--ink)"}};
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const movesHit=(m:Record<Move,boolean>)=>MOVES.filter(x=>m[x.move]).length;
export default function CallSimulator(){const [scenarioId,setScenarioId]=useState("");const [callTime,setCallTime]=useState("");const [turns,setTurns]=useState<Turn[]>([]);const [outcome,setOutcome]=useState<Outcome|null>(null);const [line,setLine]=useState("");const [waiting,setWaiting]=useState(false);const [error,setError]=useState("");const [feedback,setFeedback]=useState<Feedback|null>(null);const [scoring,setScoring]=useState(false);
const scenario=scenarios.find(s=>s.id===scenarioId);const started=outcome!==null;const over=outcome!==null&&outcome!=="ongoing";
const endRef=useRef<HTMLDivElement>(null);useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"})},[turns,waiting]);
async function merchantReply(next:Turn[]){setWaiting(true);setError("");try{const res=await authedPost("/api/roleplay",{scenarioId,callTime,turns:next});const data=await res.json();if(!res.ok)throw new Error(data.error||"The call dropped. Try again.");const r=data.feedback as {speaker:string;reply:string;callOver:boolean;outcome:Outcome};setTurns([...next,{role:"merchant",speaker:r.speaker,text:r.reply}]);setOutcome(r.callOver?(r.outcome==="ongoing"?"ended":r.outcome):"ongoing")}catch(e){setError(e instanceof Error?e.message:"The call dropped. Try again.");if(next.length===0)setOutcome(null)}finally{setWaiting(false)}}
const start=()=>{setTurns([]);setOutcome("ongoing");void merchantReply([])};
const say=()=>{stopMic();const text=line.trim();if(!text||waiting||over)return;const next:Turn[]=[...turns,{role:"rep",text}];setLine("");setTurns(next);void merchantReply(next)};
const retry=()=>{if(turns.length&&turns[turns.length-1].role==="rep")void merchantReply(turns);else if(!turns.length)start()};
const hangUp=()=>{if(turns.some(t=>t.role==="rep"))setOutcome("hung_up");else reset()};
async function getFeedback(){setScoring(true);setError("");try{const res=await authedPost("/api/roleplay-feedback",{scenarioId,callTime,turns,outcome});const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setScoring(false)}}
function reset(){stopMic();setTurns([]);setOutcome(null);setLine("");setError("");setFeedback(null)}
const tooLong=turns.length>=MAX_TURNS-1;
const mic=useDictation(text=>setLine(text));
const stopMic=()=>{if(mic.listening)mic.stop()};
return <AppShell active="Call simulator"><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><div className="eyebrow">Practice · Call simulator</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Make a practice call.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>Pick a merchant and a time, then type what you&rsquo;d say. The AI plays whoever picks up and the owner, and they react the way real people do: good calling opens them up, pushing shuts them down. When the call ends, the coach scores it against the five moves. You get five practice calls a day.</p>
{feedback&&scenario&&outcome&&outcome!=="ongoing"?<Results scenario={scenario} callTime={callTime} turns={turns} outcome={outcome} feedback={feedback} onAgain={reset}/>:!started?<div className="card" style={{marginTop:32,padding:32}}>
<small style={{fontWeight:900,letterSpacing:".1em",color:"var(--green)"}}>WHO ARE YOU CALLING?</small>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14,marginTop:14}}>{scenarios.map(s=>{const picked=s.id===scenarioId;return <button key={s.id} type="button" aria-pressed={picked} onClick={()=>setScenarioId(s.id)} style={{textAlign:"left",cursor:"pointer",border:`2px solid ${picked?"var(--green)":"var(--line)"}`,background:picked?"#f2f6e7":"white",borderRadius:14,padding:"16px 18px",font:"inherit",color:"inherit"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--green)"}}>{s.vertical.toUpperCase()}</small><div style={{fontFamily:"Georgia,serif",fontSize:20,margin:"4px 0 6px"}}>{s.business}</div><p style={{margin:0,fontSize:13,lineHeight:1.5,color:"var(--muted)"}}>{s.profile}</p></button>})}</div>
<label style={{display:"block",marginTop:22,maxWidth:320}}><span style={{display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"}}>When are you calling?</span><select style={field} value={callTime} onChange={e=>setCallTime(e.target.value)}><option value="">Choose a time…</option>{CALL_TIMES.map(t=><option key={t} value={t}>{t} on a weekday</option>)}</select></label>
<p style={{fontSize:13,color:"var(--muted)",margin:"10px 0 0"}}>Timing matters. Call when this business can actually talk.</p>
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"flex-end",marginTop:22}}><button className="btn btn-primary" disabled={!scenario||!callTime} onClick={start}>Dial →</button></div></div>
:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:"20px 28px",color:"white",display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap"}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{over?"CALL ENDED":"ON THE CALL"} · {callTime}</small><div style={{fontFamily:"Georgia,serif",fontSize:24,marginTop:4}}>{scenario?.business}</div></div>{!over&&<button className="btn btn-outline" style={{background:"white",color:RED,borderColor:"white"}} onClick={hangUp}>Hang up</button>}</div>
<div aria-live="polite" style={{padding:"22px 28px",display:"grid",gap:12,maxHeight:"55vh",overflowY:"auto",background:"#fbfcf9"}}>
{turns.map((t,i)=><div key={i} style={{justifySelf:t.role==="rep"?"end":"start",maxWidth:"78%"}}><small style={{display:"block",fontSize:11,fontWeight:800,color:"var(--muted)",margin:"0 0 4px",textAlign:t.role==="rep"?"right":"left"}}>{t.role==="rep"?"You":t.speaker}</small><div style={{padding:"11px 15px",borderRadius:14,lineHeight:1.5,whiteSpace:"pre-line",background:t.role==="rep"?"var(--green)":"white",color:t.role==="rep"?"white":"var(--ink)",border:t.role==="rep"?"none":"1px solid var(--line)"}}>{t.text}</div></div>)}
{waiting&&<div style={{justifySelf:"start",color:"var(--muted)",fontSize:14,fontStyle:"italic"}}>{turns.length?"…":"Ringing…"}</div>}
<div ref={endRef}/></div>
<div style={{padding:"18px 28px",borderTop:"1px solid var(--line)"}}>
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"0 0 12px"}}>{error} {!over&&<button className="btn btn-outline" style={{fontSize:12,minHeight:32,padding:"0 12px",marginLeft:8}} onClick={retry}>Try again</button>}</p>}
{over?<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><span style={{background:OUTCOME[outcome as Exclude<Outcome,"ongoing">].bg,color:OUTCOME[outcome as Exclude<Outcome,"ongoing">].fg,fontSize:13,fontWeight:900,padding:"6px 12px",borderRadius:20}}>{OUTCOME[outcome as Exclude<Outcome,"ongoing">].label}</span><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={reset}>Start over</button><button className="btn btn-primary" disabled={scoring} onClick={()=>void getFeedback()}>{scoring?"Scoring your call…":"Get coach feedback →"}</button></div></div>
:<><div style={{display:"flex",gap:10,alignItems:"flex-end"}}><textarea aria-label="What you say" style={{...field,minHeight:58,resize:"vertical",flex:1}} maxLength={MAX_REP_CHARS} value={line} disabled={waiting} onChange={e=>setLine(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();say()}}} placeholder={turns.length?"Type what you say, then press Enter":"Waiting for them to pick up…"}/>{mic.supported&&<button type="button" className={mic.listening?"btn btn-primary":"btn btn-outline"} aria-pressed={mic.listening} disabled={waiting||!turns.length} onClick={()=>mic.listening?mic.stop():mic.start(line)} title={mic.listening?"Stop talking":"Talk instead of typing"} style={mic.listening?{background:RED,borderColor:RED}:undefined}>{mic.listening?"■ Stop":"🎤 Talk"}</button>}<button className="btn btn-primary" disabled={waiting||!line.trim()||!turns.length} onClick={say}>Say it</button></div><p style={{fontSize:12,color:"var(--muted)",margin:"8px 0 0"}}>{tooLong?"Time to wrap up: this call is about as long as a cold call should be.":mic.listening?"Listening… speak your line, then press Stop and check it before you send.":mic.error?mic.error:`Enter to send · Shift+Enter for a new line${mic.supported?" · or press Talk and say it out loud":""}`}</p></>}
</div></div>}
<p style={{marginTop:24,fontSize:13,color:"var(--muted)"}}>Want to warm up first? Review <Link href="/courses/vertical-practice/lessons/restaurant-lab" style={{color:"var(--green)",fontWeight:800}}>the call labs</Link> or <Link href="/courses/certification/lessons/the-whole-call" style={{color:"var(--green)",fontWeight:800}}>the whole call on one page</Link>.</p>
</div></AppShell>}
function Results({scenario,callTime,turns,outcome,feedback,onAgain}:{scenario:Scenario;callTime:string;turns:Turn[];outcome:Exclude<Outcome,"ongoing">;feedback:Feedback;onAgain:()=>void}){const o=OUTCOME[outcome];const hit=movesHit(feedback.moves);
const saveStatus=useSaveExercise({type:"roleplay",moduleSlug:"vertical-practice",itemId:"roleplay",complete:false,title:`Practice call: ${scenario.business} · ${o.label}`,data:{scenario:scenario.business,vertical:scenario.vertical,callTime,outcome,outcomeLabel:o.label,verdictLabel:`${hit} of 5 moves`,transcript:turns.map(t=>`${t.role==="rep"?"You":t.speaker}: ${t.text}`).join("\n"),movesHit:hit,summary:feedback.summary,bestLine:feedback.bestLine,turningPoint:feedback.turningPoint,tryInstead:feedback.tryInstead,oneChange:feedback.oneChange}});
const block=(label:string,body:React.ReactNode)=><div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>{label}</small><div style={{marginTop:8,lineHeight:1.6}}>{body}</div></div>;
return <div style={{marginTop:32}}><section className="card" style={{overflow:"hidden"}}><div style={{background:outcome==="booked"?"var(--green)":"var(--ink)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>COACH FEEDBACK · {callTime}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 8px"}}>{scenario.business}</h2><span style={{background:o.bg,color:o.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{o.label}</span><span style={{fontSize:13,color:"#c9dbd5",marginLeft:12}}>Five moves: {hit} of 5</span></div><div style={{padding:"10px 34px 28px"}}>
<p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"16px 0"}}>{feedback.summary}</p>
{block("THE FIVE MOVES",<div style={{display:"grid",gap:8}}>{MOVES.map(m=><div key={m.move} style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,flex:"none",borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:feedback.moves[m.move]?"var(--green)":RED}}>{feedback.moves[m.move]?"✓":"!"}</span>{m.label}</div>)}</div>)}
{block("YOUR BEST LINE",feedback.bestLine)}
{block("THE TURNING POINT",<><p style={{margin:0}}>{feedback.turningPoint}</p><div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0"}}>{feedback.tryInstead}</p></div></>)}
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE FOR YOUR NEXT CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<details style={{marginTop:20}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:14}}>Read the full call</summary><div style={{marginTop:12,display:"grid",gap:8}}>{turns.map((t,i)=><p key={i} style={{margin:0,lineHeight:1.5}}><b style={{color:t.role==="rep"?"var(--green)":"var(--ink)"}}>{t.role==="rep"?"You":t.speaker}:</b> {t.text}</p>)}</div></details>
</div></section>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><button className="btn btn-primary" onClick={onAgain}>Make another call →</button><Link className="btn btn-outline" href="/progress">See my journal</Link></div><SavedNote status={saveStatus}/></div>}
// Browser speech-to-text for the rep's lines (Web Speech API: Chrome, Edge and Safari; the Talk button hides elsewhere). What they say is added to the text box, so they can check and fix it before sending. Chrome does the recognition on Google's servers.
type Recognition={lang:string;continuous:boolean;interimResults:boolean;start:()=>void;stop:()=>void;abort:()=>void;onresult:((e:{resultIndex:number;results:ArrayLike<ArrayLike<{transcript:string}>&{isFinal:boolean}>})=>void)|null;onend:(()=>void)|null;onerror:((e:{error:string})=>void)|null};
function useDictation(onText:(text:string)=>void){const [supported,setSupported]=useState(false);const [listening,setListening]=useState(false);const [error,setError]=useState("");const rec=useRef<Recognition|null>(null);const onTextRef=useRef(onText);onTextRef.current=onText;
useEffect(()=>{const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};setSupported(!!(w.SpeechRecognition||w.webkitSpeechRecognition));return()=>rec.current?.abort()},[]);
const start=(existing:string)=>{const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const Ctor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Ctor)return;
 const r=new Ctor();r.lang="en-US";r.continuous=true;r.interimResults=true;const base=existing.trim();let finalText="";
 r.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const res=e.results[i];if(res.isFinal)finalText+=res[0].transcript;else interim+=res[0].transcript}onTextRef.current([base,(finalText+interim).trim()].filter(Boolean).join(" "))};
 r.onerror=e=>{setError(e.error==="not-allowed"||e.error==="service-not-allowed"?"Microphone access is blocked. Allow it in your browser's address bar, or type instead.":e.error==="no-speech"?"Didn't catch that. Press Talk and try again.":"Speech-to-text stopped. Press Talk to try again, or type instead.")};
 r.onend=()=>{setListening(false);rec.current=null};
 setError("");rec.current=r;r.start();setListening(true)};
const stop=()=>{rec.current?.stop()};
return {supported,listening,error,start,stop}}
