"use client"; import { useState } from "react"; import Link from "next/link"; import { AppShell } from "@/components/AppShell"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadReflectionPdf } from "@/lib/pdf";
type Feedback={verdict:"strong"|"close"|"needs_work";summary:string;thoughtPattern:string;whatWorked:string;leftovers:string[];suggestedRewrite:string};
const VERDICT={strong:{label:"Facts only",bg:"var(--green)",fg:"white"},close:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)"},needs_work:{label:"Keep working",bg:"#f3d9c9",fg:"#7a2e0e"}};
// Steps 1 and 2 (the thought + its facts-only rewrite) get AI coaching from /api/reframe-feedback before moving on to step 3.
const FEEDBACK_STEP=1;
export default function Practice(){const [step,setStep]=useState(0);const [answers,setAnswers]=useState(["","",""]);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [done,setDone]=useState(false);const prompts=["Write the thought that usually shows up right before you avoid making a call.","Rewrite that thought using only facts—remove predictions and judgments.","Write one action you can control on the next call."];
const update=(v:string)=>{setAnswers(a=>a.map((x,i)=>i===step?v:x));if(step<=FEEDBACK_STEP){setFeedback(null);setError("")}};
async function getFeedback(){setLoading(true);setError("");try{const res=await fetch("/api/reframe-feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({thought:answers[0],rewrite:answers[1]})});const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const needsFeedback=step===FEEDBACK_STEP&&!feedback;const canAdvance=answers[step].trim().length>0;
const onPrimary=()=>{if(needsFeedback){void getFeedback();return}if(step===2){setDone(true);window.scrollTo(0,0);return}setStep(step+1)};
const restart=()=>{setAnswers(["","",""]);setFeedback(null);setError("");setStep(0);setDone(false)};
const primaryLabel=step===2?"Save reflection":needsFeedback?(loading?"Getting feedback…":"Get coach feedback →"):"Continue →";
return <AppShell active="Practice"><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="understanding-call-reluctance" itemId="reframe"/><div className="eyebrow">Guided practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Reframe the rejection.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:700}}>Turn an automatic fear response into a specific, useful next action. When you finish, you&apos;ll get a summary you can download and keep.</p>{done&&feedback?<Summary answers={answers} feedback={feedback} onRestart={restart}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between"}}><div><small style={{color:"var(--lime)",fontWeight:900}}>SCENARIO</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>The first call block of the day</h2></div><span style={{fontSize:13,color:"#c9dbd5"}}>Step {step+1} of 3</span></div><div style={{padding:36}}>{step===FEEDBACK_STEP&&answers[0].trim()&&<div style={{borderLeft:"4px solid var(--line)",padding:"4px 0 4px 16px",marginBottom:22}}><small style={{color:"var(--muted)",fontWeight:900,letterSpacing:".1em"}}>YOUR THOUGHT</small><p style={{margin:"6px 0 0",fontStyle:"italic",lineHeight:1.5}}>&ldquo;{answers[0].trim()}&rdquo;</p></div>}<p style={{fontSize:20,fontFamily:"Georgia,serif",lineHeight:1.5,marginTop:0}}>{prompts[step]}</p><textarea value={answers[step]} onChange={e=>update(e.target.value)} maxLength={1500} placeholder="Write your response here..." style={{width:"100%",minHeight:170,border:"1px solid var(--line)",borderRadius:12,padding:17,resize:"vertical",background:"#fbfcf9",lineHeight:1.6}}/>
{error&&<p role="alert" style={{color:"#a3320b",fontSize:14,margin:"14px 0 0"}}>{error}</p>}
{step===FEEDBACK_STEP&&feedback&&<FeedbackPanel f={feedback} onUse={()=>setAnswers(a=>a.map((x,i)=>i===FEEDBACK_STEP?feedback.suggestedRewrite:x))}/>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:22}}>{step===0?<Link className="btn btn-outline" href="/courses/understanding-call-reluctance/lessons/avoidance-loop">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{prompts.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{primaryLabel}</button></div></div></div>}<ModulePager moduleSlug="understanding-call-reluctance" itemId="reframe"/></div></AppShell>}
function FeedbackPanel({f,onUse}:{f:Feedback;onUse:()=>void}){const v=VERDICT[f.verdict];return <section aria-live="polite" style={{marginTop:24,border:"1px solid var(--line)",borderRadius:12,background:"#f7f9f2",padding:24}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:18,lineHeight:1.5,margin:"14px 0"}}>{f.summary}</p><div style={{display:"grid",gap:12,fontSize:15,lineHeight:1.55}}><div><b>Your original thought was:</b> <span style={{color:"var(--muted)"}}>{f.thoughtPattern}</span></div><div><b>What worked:</b> <span style={{color:"var(--muted)"}}>{f.whatWorked}</span></div>{f.leftovers.length>0&&<div><b>Still a prediction or judgment:</b><ul style={{margin:"6px 0 0",paddingLeft:20,color:"var(--muted)"}}>{f.leftovers.map((l,i)=><li key={i}>&ldquo;{l}&rdquo;</li>)}</ul></div>}</div>{f.verdict!=="strong"&&<div style={{marginTop:18,background:"white",border:"1px solid var(--line)",borderRadius:10,padding:16}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>A TIGHTER VERSION</small><p style={{margin:"8px 0 12px",lineHeight:1.55}}>{f.suggestedRewrite}</p><button className="btn btn-outline" onClick={onUse} style={{fontSize:13}}>Use this version</button></div>}<p style={{fontSize:12,color:"var(--muted)",margin:"14px 0 0"}}>Edit your rewrite to get new feedback, or continue to the last step.</p></section>}
// Finish screen after "Save reflection": saves the reflection to the rep's journal, and offers it as a PDF (see lib/pdf.ts).
function Summary({answers,feedback,onRestart}:{answers:string[];feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const showTighter=feedback.verdict!=="strong"&&!!feedback.suggestedRewrite.trim()&&feedback.suggestedRewrite.trim()!==answers[1].trim();const [pdfError,setPdfError]=useState("");const saveStatus=useSaveExercise({type:"reflection",moduleSlug:"understanding-call-reluctance",itemId:"reframe",title:"Reframe the Rejection",data:{thought:answers[0],rewrite:answers[1],action:answers[2],verdict:feedback.verdict,verdictLabel:v.label,coachSummary:feedback.summary,tighterVersion:showTighter?feedback.suggestedRewrite:""}});const downloadPdf=()=>{setPdfError("");downloadReflectionPdf({thought:answers[0],rewrite:answers[1],verdict:feedback.verdict,verdictLabel:v.label,coachSummary:feedback.summary,tighterVersion:showTighter?feedback.suggestedRewrite:null,action:answers[2],date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};const date=new Date().toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"});const row=(label:string,text:string,extra?:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",alignItems:"center",gap:10,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small>{extra}</div><p style={{margin:"8px 0 0",fontSize:17,lineHeight:1.55}}>{text}</p></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>REFLECTION COMPLETE</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>Reframe the rejection</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Merchant Sales Academy · {date}</span></div><div style={{padding:"16px 36px 30px"}}>{row("THE THOUGHT",answers[0].trim())}{row("YOUR FACTS-ONLY REWRITE",answers[1].trim(),<span style={{background:v.bg,color:v.fg,fontSize:11,fontWeight:900,padding:"3px 9px",borderRadius:20}}>{v.label}</span>)}{feedback.summary&&<p style={{margin:"-6px 0 16px",fontSize:14,color:"var(--muted)",lineHeight:1.5}}>Coach: {feedback.summary}</p>}{showTighter&&row("COACH’S TIGHTER VERSION",feedback.suggestedRewrite.trim())}{row("YOUR ACTION FOR THE NEXT CALL",answers[2].trim())}<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE YOUR NEXT CALL BLOCK, READ THIS</small><p style={{fontFamily:"Georgia,serif",fontSize:21,lineHeight:1.45,margin:"8px 0 0"}}>{answers[2].trim()}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Start another reflection</button></div><Link className="btn btn-primary" href="/quiz">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:"#a3320b",fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
