"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadGatekeeperPlanPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 10 exercise: for one real business, the rep plans the call with whoever answers the phone: the introduction, the questions that ask for help, how to handle a no, and how to make an ally. Coach feedback (plus what to say once put through to the owner) comes from /api/gatekeeper-plan-feedback, then the plan can be kept as a PDF.
type StepKey="merchant"|"intro"|"help"|"theNo"|"ally";
type Area=Exclude<StepKey,"merchant">;
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;ownerOpener:string;oneChange:string};
type Draft={vertical:string;merchant:string;answerer:string;intro:string;help:string;theNo:string;ally:string};
const EMPTY:Draft={vertical:"",merchant:"",answerer:"",intro:"",help:"",theNo:"",ally:""};
const VERTICALS=["Restaurant","Retail","Service business (salon, auto, contractor)","Medical or dental office","E-commerce","Other"];
const VERDICT={ready:{label:"Ready to call",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string;placeholder:string}[]=[
 {key:"merchant",kicker:"THE BUSINESS",title:"Pick a real business where someone else answers the phone.",hint:"A business on your list where you’re likely to reach a host, cashier, service writer, office manager or family member before the owner.",placeholder:""},
 {key:"intro",kicker:"THE INTRODUCTION",title:"What will you say when they pick up?",hint:"Your name, your company and an honest reason about their business, plus asking for their name. Write your answer to “What’s this regarding?” too. No tricks.",placeholder:"e.g. “Hi, this is Alex with BytePOS. I help restaurants around here figure out what they’re really paying to take cards. Who am I speaking with?” If they ask what it’s regarding: “I’d like to offer Maria a quick look at her processing statement, to see if her fees make sense.”"},
 {key:"help",kicker:"ASK FOR HELP",title:"What will you ask instead of “Is the owner in?”",hint:"Who handles card processing, when’s a good time, and how to reach them. Add one easy question about what they see every day, and how you’ll use what they tell you.",placeholder:"e.g. “Who usually looks after the card machines, Maria or someone else?” “When’s a quieter time to catch her for two minutes?” “Does the terminal ever give you trouble on busy nights?” If they say Tuesday after two, I call Tuesday after two and say Jenna suggested it."},
 {key:"theNo",kicker:"WHEN IT’S A NO",title:"What will you do if the answer is no?",hint:"How you’ll accept it, thank them, and leave the door open. What changes if they say the business doesn’t take sales calls at all?",placeholder:"e.g. “No problem, thanks for letting me know, Jenna. Would it be all right if I checked back in the spring?” If they don’t take sales calls, I note it in the CRM and don’t call the main line again. Maybe drop by at 3 p.m. on a weekday, or send Maria a short letter."},
 {key:"ally",kicker:"MAKE AN ALLY",title:"How will you turn them into an ally?",hint:"What goes in the CRM, how you’ll thank them, the promises you’ll keep, and how your next call will open.",placeholder:"e.g. Log Jenna (host), what she told me and the best time to call. Thank her by name before I hang up. If I said two minutes with Maria, it’s two minutes. Next call: “Hi Jenna, it’s Alex. You said Tuesdays are quieter, so here I am.”"},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"intro",title:"Introduction",step:1},{area:"help",title:"Asking for help",step:2},{area:"theNo",title:"When it’s a no",step:3},{area:"ally",title:"Making an ally",step:4}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
const unquote=(t:string)=>t.trim().replace(/^["“]+|["”]+$/g,"");
function filled(d:Draft,key:StepKey){return key==="merchant"?!!(d.vertical&&d.merchant.trim()&&d.answerer.trim()):!!d[key].trim()}
export default function GatekeeperPlanPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/gatekeeper-plan-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="gatekeepers")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="gatekeepers" itemId="gatekeeper-plan"/><div className="eyebrow">Module 10 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Plan your front-desk call.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>For one real business where someone else answers the phone, plan the call with them: how you&rsquo;ll introduce yourself, what you&rsquo;ll ask instead of &ldquo;Is the owner in?&rdquo;, what you&rsquo;ll do if it&rsquo;s a no, and how you&rsquo;ll turn them into an ally. The coach checks it against the lessons and writes what to say once you&rsquo;re put through to the owner.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="merchant"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Vertical</span><select style={field} value={draft.vertical} onChange={e=>update({vertical:e.target.value})}><option value="">Choose one…</option>{VERTICALS.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span style={labelStyle}>Business</span><input style={field} maxLength={1500} value={draft.merchant} onChange={e=>update({merchant:e.target.value})} placeholder="e.g. Casa Verde, family restaurant"/></label><label><span style={labelStyle}>Who usually answers</span><input style={field} maxLength={1500} value={draft.answerer} onChange={e=>update({answerer:e.target.value})} placeholder="e.g. The host at the front stand"/></label></div>
:<textarea style={{...field,minHeight:160,resize:"vertical"}} maxLength={1500} value={draft[current.key]} onChange={e=>update({[current.key]:e.target.value})} placeholder={current.placeholder}/>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/gatekeepers/lessons/make-an-ally">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your plan…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="gatekeepers" itemId="gatekeeper-plan"/></div></PreviewGate></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONCE YOU’RE PUT THROUGH</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>&ldquo;{unquote(feedback.ownerOpener)}&rdquo;</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the plan as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my plan</button><button className="btn btn-primary" onClick={onSave}>Save my plan →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const saveStatus=useSaveExercise({type:"gatekeeper-plan",moduleSlug:"gatekeepers",itemId:"gatekeeper-plan",title:`Front-desk plan: ${draft.merchant}`,data:{vertical:draft.vertical,merchant:draft.merchant,answerer:draft.answerer,intro:draft.intro,help:draft.help,theNo:draft.theNo,ally:draft.ally,ownerOpener:unquote(feedback.ownerOpener),verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadGatekeeperPlanPdf({vertical:draft.vertical,merchant:draft.merchant,answerer:draft.answerer,intro:draft.intro,help:draft.help,theNo:draft.theNo,ally:draft.ally,ownerOpener:unquote(feedback.ownerOpener),coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55,whiteSpace:"pre-line"}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>PLAN SAVED · {draft.vertical.toUpperCase()}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{draft.merchant}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Who answers: {draft.answerer} · Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("INTRODUCTION",draft.intro)}
{row("ASKING FOR HELP",draft.help)}
{row("WHEN IT’S A NO",draft.theNo)}
{row("MAKING AN ALLY",draft.ally)}
{row("ONCE YOU’RE PUT THROUGH",<p style={{fontFamily:"Georgia,serif",fontSize:18,margin:0}}>&ldquo;{unquote(feedback.ownerOpener)}&rdquo;</p>)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Plan another call</button></div><Link className="btn btn-primary" href="/quiz/gatekeepers">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
