"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadFinalScenarioPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum"; import { scenarios, type Scenario } from "@/data/scenarios";
// Module 12 certification call: the rep picks a merchant from data/scenarios.ts and writes the whole call in six parts. The coach (/api/final-scenario-feedback) grades each part; the call passes only when every part is "good", and only a passing call marks the exercise complete toward certification. Every attempt is saved to the journal and can be kept as a PDF.
type Area="timing"|"frontDesk"|"opener"|"objection"|"ask"|"followUp";
type Move="intro"|"question"|"steady"|"number"|"time";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={summary:string;strength:string;sections:Record<Area,Section>;moves:Record<Move,boolean>;oneChange:string};
type Draft={scenarioId:string}&Record<Area,string>;
type Verdict="pass"|"almost"|"not_yet";
const EMPTY:Draft={scenarioId:"",timing:"",frontDesk:"",opener:"",objection:"",ask:"",followUp:""};
const VERDICT={pass:{label:"Passed",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},not_yet:{label:"Not yet",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{area:Area;kicker:string;title:string;hint:(s:Scenario)=>string;placeholder:string}[]=[
 {area:"timing",kicker:"TIMING AND REASON",title:"When will you call, and why this business?",hint:s=>`Pick a time that fits how ${s.business} runs its day and when ${s.decisionMaker.split(",")[0]} can talk. Then write your reason for calling, using a detail from the profile.`,placeholder:"e.g. I’ll call at 2:30 p.m., after the lunch rush and before dinner prep. My reason: they just started catering, and I help restaurants see what new kinds of orders are really costing them to take payment on."},
 {area:"frontDesk",kicker:"THE FRONT DESK",title:"What will you say to whoever answers?",hint:s=>`${s.answerer} usually picks up. Write your introduction, how you’ll ask for help instead of access, and your answer to “What’s this regarding?”`,placeholder:"e.g. “Hi, this is Alex with BytePOS. I help restaurants around here with what they pay to take cards. Who am I speaking with? … Thanks, Marcus. Who usually handles that, Lucia or someone else? When’s a good time to catch her for two minutes?”"},
 {area:"opener",kicker:"OPENER AND DISCOVERY",title:"What will you say to the decision-maker, and what will you ask?",hint:s=>`Your opener to ${s.decisionMaker.split(",")[0]}: who you are, your reason, and one easy question. Then at least two discovery questions, and how you’d follow their answer.`,placeholder:"e.g. “Hi Lucia, Alex with BytePOS. Marcus said this was a good time. I saw you started catering this year. Are those orders paid at pickup, or invoiced ahead?” Then: “How big is a typical catering order?” and “What happens when someone pays late?” If she says invoices are slow, I’ll ask how long they usually wait."},
 {area:"objection",kicker:"THE OBJECTION",title:"They push back. What do you say?",hint:s=>`Partway through the call, ${s.decisionMaker.split(",")[0]} says: “${s.objection}” Write exactly how you’ll respond.`,placeholder:"Write what you’d say, word for word, and what you’d do if they push back a second time."},
 {area:"ask",kicker:"THE ASK",title:"How will you ask for the meeting?",hint:()=>"One number in their terms, a small next step instead of a switch, a specific day and time that fits the business, and what they should bring or send.",placeholder:"e.g. “On a $400 catering order, the card fees alone add up fast. Send me last month’s statement and I’ll show you what you’re really paying. If it’s fair, I’ll say so. Could we take fifteen minutes Thursday at 3, before dinner prep?”"},
 {area:"followUp",kicker:"THE FOLLOW-UP",title:"What happens after you hang up?",hint:()=>"What you send right after the call, and what you’ll do if they go quiet or don’t show: how many touches, what each one adds, and when you close the file.",placeholder:"e.g. Same day: a short email confirming Thursday at 3, using her words about catering, and what to send. If she goes quiet: a call two days later with one useful idea, an email a week later, then one last note saying I’ll close the file unless she wants to pick it up."},
];
const AREAS:{area:Area;title:string}[]=[{area:"timing",title:"Timing and reason"},{area:"frontDesk",title:"The front desk"},{area:"opener",title:"Opener and discovery"},{area:"objection",title:"The objection"},{area:"ask",title:"The ask"},{area:"followUp",title:"The follow-up"}];
const MOVES:{move:Move;label:string}[]=[{move:"intro",label:"Who you are and why you’re calling"},{move:"question",label:"A question about their business"},{move:"steady",label:"Steady through the first no"},{move:"number",label:"One number in their terms"},{move:"time",label:"A specific day and time"}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const verdictOf=(f:Feedback):Verdict=>{const fixes=AREAS.filter(a=>f.sections[a.area].status==="fix").length;return fixes===0?"pass":fixes===1?"almost":"not_yet"};
const movesHit=(m:Record<Move,boolean>)=>MOVES.filter(x=>m[x.move]).length;
function ScenarioCard({s,compact}:{s:Scenario;compact?:boolean}){return <div style={{background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:12,padding:compact?"14px 18px":"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--green)"}}>{s.vertical.toUpperCase()}</small><div style={{fontFamily:"Georgia,serif",fontSize:compact?19:22,margin:"4px 0 6px"}}>{s.business}</div><p style={{margin:0,fontSize:14,lineHeight:1.55,color:"var(--muted)"}}>{s.profile}</p><p style={{margin:"8px 0 0",fontSize:13,lineHeight:1.5}}><b>Answers the phone:</b> {s.answerer} · <b>Decides:</b> {s.decisionMaker}</p></div>}
export default function FinalScenario(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const scenario=scenarios.find(s=>s.id===draft.scenarioId);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/final-scenario-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const total=STEPS.length+1;const current=step>0?STEPS[step-1]:null;const canAdvance=step===0?!!scenario:!!draft[current!.area].trim();
const onPrimary=()=>{if(step<STEPS.length){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false);setDone(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="certification")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="certification" itemId="final-scenario"/><div className="eyebrow">Module 12 certification · 15 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Final scenario call.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>Pick a merchant and write the whole call: when and why you&rsquo;re calling, the front desk, your opener and discovery, the objection, the ask and the follow-up. The coach grades all six parts. Your call passes when every part follows what the course teaches, and you can revise and resubmit as many times as you need.</p>
{done&&feedback&&scenario?<Summary draft={draft} scenario={scenario} feedback={feedback} onRevise={()=>{setDone(false);setReviewing(true);window.scrollTo(0,0)}} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current?current.kicker:"THE MERCHANT"}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current?current.title:"Pick the merchant you’ll call."}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {total}</span></div><div style={{padding:36}}>
{step===0?<><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>Each one is a different kind of business with a different objection. Pick one you don’t call every day if you want the real test.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14}}>{scenarios.map(s=>{const picked=s.id===draft.scenarioId;return <button key={s.id} type="button" aria-pressed={picked} onClick={()=>update({scenarioId:s.id})} style={{textAlign:"left",cursor:"pointer",border:`2px solid ${picked?"var(--green)":"var(--line)"}`,background:picked?"#f2f6e7":"white",borderRadius:14,padding:"16px 18px",font:"inherit",color:"inherit"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--green)"}}>{s.vertical.toUpperCase()}</small><div style={{fontFamily:"Georgia,serif",fontSize:20,margin:"4px 0 6px"}}>{s.business}</div><p style={{margin:0,fontSize:13,lineHeight:1.5,color:"var(--muted)"}}>{s.profile}</p></button>})}</div></>
:scenario&&current&&<><div style={{marginBottom:20}}><ScenarioCard s={scenario} compact/></div><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint(scenario)}</p><textarea style={{...field,minHeight:170,resize:"vertical"}} maxLength={1500} value={draft[current.area]} onChange={e=>update({[current.area]:e.target.value})} placeholder={current.placeholder}/></>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/certification/lessons/next-30-days">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{Array.from({length:total},(_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length?"Continue →":feedback?"Back to feedback →":loading?"Grading your call…":"Submit for grading →"}</button></div></div></div>}<ModulePager moduleSlug="certification" itemId="final-scenario"/></div></PreviewGate></AppShell>}
function MoveList({moves}:{moves:Record<Move,boolean>}){return <div style={{display:"grid",gap:8,marginTop:10}}>{MOVES.map(m=><div key={m.move} style={{display:"flex",alignItems:"center",gap:10,fontSize:15}}><span style={{width:22,height:22,flex:"none",borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:moves[m.move]?"var(--green)":RED}}>{moves[m.move]?"✓":"!"}</span>{m.label}</div>)}</div>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const verdict=verdictOf(feedback);const v=VERDICT[verdict];const fixes=AREAS.filter(a=>feedback.sections[a.area].status==="fix").length;return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>CERTIFICATION GRADE</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p><p style={{margin:"0 0 6px",lineHeight:1.6,color:"var(--muted)"}}><b style={{color:"var(--ink)"}}>Best part:</b> {feedback.strength}</p>
{verdict!=="pass"&&<p style={{margin:"10px 0 0",fontSize:14,lineHeight:1.55,color:RED}}>{fixes===1?"One part needs a fix before this call passes.":`${fixes} parts need a fix before this call passes.`} Edit them and resubmit.</p>}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)",marginTop:14}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>THE FIVE MOVES · {movesHit(feedback.moves)} OF 5</small><MoveList moves={feedback.moves}/></div>
{AREAS.map((a,i)=>({...a,step:i+1,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>{verdict==="pass"?"PROTECT THIS ON LIVE CALLS":"THE MOST IMPORTANT FIX"}</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>{verdict==="pass"?"Save your passing call to count it toward certification.":"Edit any part and resubmit, or save this attempt to your journal. Only a passing call counts toward certification."}</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my call</button><button className="btn btn-primary" onClick={onSave}>{verdict==="pass"?"Save my passing call →":"Save this attempt →"}</button></div></section>}
function Summary({draft,scenario,feedback,onRevise,onRestart}:{draft:Draft;scenario:Scenario;feedback:Feedback;onRevise:()=>void;onRestart:()=>void}){const verdict=verdictOf(feedback);const v=VERDICT[verdict];const passed=verdict==="pass";const [pdfError,setPdfError]=useState("");const hit=movesHit(feedback.moves);
const saveStatus=useSaveExercise({type:"final-scenario",moduleSlug:"certification",itemId:"final-scenario",complete:passed,title:`Final scenario: ${scenario.business}${passed?"":" (not yet passed)"}`,data:{scenario:scenario.business,vertical:scenario.vertical,objectionGiven:scenario.objection,timing:draft.timing,frontDesk:draft.frontDesk,opener:draft.opener,objection:draft.objection,ask:draft.ask,followUp:draft.followUp,movesHit:hit,passed,verdict,verdictLabel:v.label,strength:feedback.strength,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadFinalScenarioPdf({business:scenario.business,vertical:scenario.vertical,profile:scenario.profile,objectionGiven:scenario.objection,timing:draft.timing,frontDesk:draft.frontDesk,opener:draft.opener,objection:draft.objection,ask:draft.ask,followUp:draft.followUp,sections:AREAS.map(a=>({title:a.title,good:feedback.sections[a.area].status==="good"})),strength:feedback.strength,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode,good?:boolean)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:good===false?RED:"var(--muted)"}}>{label}{good===false?" · NEEDS A FIX":""}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55,whiteSpace:"pre-line"}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:passed?"var(--green)":"var(--ink)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>{passed?"CERTIFICATION CALL PASSED":"ATTEMPT SAVED · NOT YET PASSED"}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{scenario.business}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>{scenario.vertical} · Objection: “{scenario.objection}” · Five moves: {hit} of 5</span></div><div style={{padding:"16px 36px 30px"}}>
{AREAS.map(a=><div key={a.area}>{row(a.title.toUpperCase(),draft[a.area],feedback.sections[a.area].status==="good")}</div>)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>{passed?"PROTECT THIS ON LIVE CALLS":"THE MOST IMPORTANT FIX"}</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Try a different merchant</button></div>{passed?<Link className="btn btn-primary" href="/quiz/certification">Continue to the Final Exam →</Link>:<button className="btn btn-primary" onClick={onRevise}>Revise and resubmit →</button>}</div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
