"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadPitchCardPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 4 exercise: the rep builds a pitch card for one real merchant (vertical pain + call time, their number, a peer example, a software question), gets coach feedback from /api/pitch-card-feedback, then keeps the card as a PDF.
type StepKey="merchant"|"pain"|"number"|"example"|"software";
type Area="pain"|"number"|"example"|"software";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;cheatSheet:string;oneChange:string};
type Draft={vertical:string;merchant:string;callTime:string;pain:string;number:string;example:string;exampleIsReal:boolean|null;software:string};
const EMPTY:Draft={vertical:"",merchant:"",callTime:"",pain:"",number:"",example:"",exampleIsReal:null,software:""};
const VERTICALS=["Restaurant","Retail","Service business (salon, auto, contractor)","E-commerce","Other"];
const VERDICT={ready:{label:"Ready to call",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string}[]=[
 {key:"merchant",kicker:"THE MERCHANT",title:"Pick a real merchant and its vertical.",hint:"Someone on your list this week. Then decide when this kind of business can actually talk."},
 {key:"pain",kicker:"THEIR PAIN",title:"What does this vertical lose sleep over?",hint:"The problem this kind of business runs into every week. Not rates: those are what every merchant has in common. Treat it as a guess to ask about."},
 {key:"number",kicker:"THEIR NUMBER",title:"Pick one number, in their units.",hint:"Covers and average ticket for restaurants, basket size for retail, jobs per week or days until paid for service businesses, orders for e-commerce. Use a range they can confirm, not a made-up figure."},
 {key:"example",kicker:"A BUSINESS LIKE THEIRS",title:"Who have you helped that's like them?",hint:"One sentence about a real customer: same kind of business, size, area or situation. No close match? Describe the situation honestly instead. Never invent a customer."},
 {key:"software",kicker:"THEIR SOFTWARE",title:"What will you ask about their software?",hint:"Ask what they run before you mention what you sell. Easy to answer, and no promised integration you haven't confirmed."},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"pain",title:"Pain and timing",step:1},{area:"number",title:"Their number",step:2},{area:"example",title:"Business like theirs",step:3},{area:"software",title:"Software question",step:4}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
function filled(d:Draft,key:StepKey){switch(key){case "merchant":return !!(d.vertical&&d.merchant.trim()&&d.callTime.trim());case "pain":return !!d.pain.trim();case "number":return !!d.number.trim();case "example":return d.exampleIsReal!==null&&!!d.example.trim();case "software":return !!d.software.trim()}}
export default function PitchCardPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/pitch-card-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
const choice=(on:boolean)=>({padding:"12px 16px",borderRadius:12,border:`1px solid ${on?"var(--green)":"var(--line)"}`,background:on?"#edf5ef":"white",textAlign:"left" as const,cursor:"pointer",lineHeight:1.45,color:"var(--ink)"});
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="earning-attention")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="earning-attention" itemId="pitch-card"/><div className="eyebrow">Module 4 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Build your vertical pitch card.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>For one real merchant on your list: the problem their kind of business has, the one number that matters to them, a business like theirs, and the question about their software. The coach checks it against the lessons, and you keep the card for your next call block.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="merchant"&&<div style={{display:"grid",gap:18}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Vertical</span><select style={field} value={draft.vertical} onChange={e=>update({vertical:e.target.value})}><option value="">Choose one…</option>{VERTICALS.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span style={labelStyle}>Business</span><input style={field} maxLength={1000} value={draft.merchant} onChange={e=>update({merchant:e.target.value})} placeholder="e.g. Harbor Cuts, a two-chair barbershop"/></label></div><label><span style={labelStyle}>Best time to call them, and why</span><input style={field} maxLength={1000} value={draft.callTime} onChange={e=>update({callTime:e.target.value})} placeholder="e.g. 9:30 a.m., before the first appointments stack up"/></label></div>}
{current.key==="pain"&&<textarea style={{...field,minHeight:130,resize:"vertical"}} maxLength={1000} value={draft.pain} onChange={e=>update({pain:e.target.value})} placeholder="e.g. No-shows. Barbers lose the chair time and most small shops don't take deposits."/>}
{current.key==="number"&&<textarea style={{...field,minHeight:120,resize:"vertical"}} maxLength={1000} value={draft.number} onChange={e=>update({number:e.target.value})} placeholder="e.g. Shops like theirs lose two or three appointments a week. At $35 a cut, that's about $100 a week. Is that close?"/>}
{current.key==="example"&&<div style={{display:"grid",gap:14}}><div style={{display:"grid",gap:10}}><button type="button" style={choice(draft.exampleIsReal===true)} onClick={()=>update({exampleIsReal:true})}><b>A real customer like them</b><br/><small style={{color:"var(--muted)"}}>You or your team set them up. Check with your manager before naming them on a call.</small></button><button type="button" style={choice(draft.exampleIsReal===false)} onClick={()=>update({exampleIsReal:false})}><b>No close match yet</b><br/><small style={{color:"var(--muted)"}}>Describe the situation honestly instead: &ldquo;Shops that just added a second chair usually tell us…&rdquo;</small></button></div><textarea style={{...field,minHeight:110,resize:"vertical"}} maxLength={1000} value={draft.example} onChange={e=>update({example:e.target.value})} placeholder="One sentence."/></div>}
{current.key==="software"&&<input style={field} maxLength={1000} value={draft.software} onChange={e=>update({software:e.target.value})} placeholder="e.g. What are you using to book appointments right now?"/>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/earning-attention/lessons/fit-the-software-they-run">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your card…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="earning-attention" itemId="pitch-card"/></div></PreviewGate></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>YOUR CHEAT SHEET FOR THIS VERTICAL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>{feedback.cheatSheet}</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the card as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my card</button><button className="btn btn-primary" onClick={onSave}>Save my card →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const exampleLabel=draft.exampleIsReal?"A BUSINESS LIKE THEIRS":"THE SITUATION (NO CLOSE MATCH YET)";const saveStatus=useSaveExercise({type:"pitch-card",moduleSlug:"earning-attention",itemId:"pitch-card",title:`Pitch card: ${draft.merchant}`,data:{vertical:draft.vertical,merchant:draft.merchant,callTime:draft.callTime,pain:draft.pain,number:draft.number,example:draft.example,exampleIsReal:!!draft.exampleIsReal,software:draft.software,cheatSheet:feedback.cheatSheet,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadPitchCardPdf({vertical:draft.vertical,merchant:draft.merchant,callTime:draft.callTime,pain:draft.pain,number:draft.number,exampleLabel,example:draft.example,software:draft.software,cheatSheet:feedback.cheatSheet,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>CARD SAVED · {draft.vertical.toUpperCase()}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{draft.merchant}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Call: {draft.callTime} · Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
<div style={{margin:"12px 0 6px",background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"14px 18px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>CHEAT SHEET</small><p style={{fontFamily:"Georgia,serif",fontSize:18,margin:"6px 0 0",lineHeight:1.5}}>{feedback.cheatSheet}</p></div>
{row("THEIR PAIN",draft.pain)}
{row("THEIR NUMBER",draft.number)}
{row(exampleLabel,draft.example)}
{row("ASK ABOUT THEIR SOFTWARE",<p style={{fontFamily:"Georgia,serif",fontSize:18,margin:0}}>&ldquo;{draft.software}&rdquo;</p>)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Build another card</button></div><Link className="btn btn-primary" href="/quiz/earning-attention">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
