"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadConsistencyPlanPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 9 exercise: the rep enters last week's real numbers, then writes next week's input goals, where the numbers leak and the one fix, a first-dial habit, and an honest rewrite of the story after a bad week. Coach feedback (plus a Monday-morning start) comes from /api/consistency-plan-feedback, then the plan can be kept as a PDF.
type StepKey="numbers"|"inputs"|"leak"|"habit"|"story";
type Area=Exclude<StepKey,"numbers">;
type Count="dials"|"conversations"|"booked"|"held";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;mondayStart:string;oneChange:string};
type Draft=Record<Count|Area,string>;
const EMPTY:Draft={dials:"",conversations:"",booked:"",held:"",inputs:"",leak:"",habit:"",story:""};
const COUNTS:{key:Count;label:string}[]=[{key:"dials",label:"Dials"},{key:"conversations",label:"Decision-maker conversations"},{key:"booked",label:"Appointments booked"},{key:"held",label:"Appointments held"}];
const VERDICT={ready:{label:"Ready for Monday",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string;placeholder:string}[]=[
 {key:"numbers",kicker:"LAST WEEK’S NUMBERS",title:"What really happened last week?",hint:"Use your CRM, not your memory. A voicemail isn’t a conversation, and “call me next week” isn’t an appointment.",placeholder:""},
 {key:"inputs",kicker:"INPUT GOALS",title:"What will you do next week, whatever the merchants do?",hint:"Goals you control and can count: call blocks finished, dials, follow-ups sent on the day you promised, calls logged. Add one quality goal if you like.",placeholder:"e.g. Both call blocks every day, 60 dials a day. Every follow-up due goes out that day. Every call logged before lunch. One real impact question on every conversation."},
 {key:"leak",kicker:"THE LEAK",title:"Where do your numbers drop off, and what’s your one fix?",hint:"Look at your ratios above. Name the weakest step and one specific thing you’ll change next week. Just one.",placeholder:"e.g. I get conversations but only 1 in 9 turns into an appointment. I think I talk about us too long and never actually ask. Fix: ask for the meeting on every call that lasts past two minutes."},
 {key:"habit",kicker:"THE FIRST DIAL",title:"How will every call block start?",hint:"The cue, the time, a first step small enough for your worst morning, and what you’ll do when a block gets missed.",placeholder:"e.g. Coffee on the desk, list open, first number dialed by 9:05, before I open email. If a meeting knocks out a block, I make it up that afternoon. Never two misses in a row."},
 {key:"story",kicker:"THE STORY",title:"How did you explain your last bad week, and what’s the honest rewrite?",hint:"Write what you told yourself, then rewrite it so it’s temporary, specific, and about something you did that can change. End with one action.",placeholder:"e.g. What I told myself: “I’m just not good at the phone.” Rewrite: “That week my list was mostly closed restaurants, and I stopped asking for the meeting after two no’s. This week I’ll ask on every good call.”"},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"inputs",title:"Input goals",step:1},{area:"leak",title:"The leak and the fix",step:2},{area:"habit",title:"First-dial habit",step:3},{area:"story",title:"The story, rewritten",step:4}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
const num=(v:string)=>Number.parseInt(v,10);
function ratios(d:Draft){const [a,b,c,h]=COUNTS.map(k=>num(d[k.key]));const r=(x:number,y:number,one:string,many:string)=>y>0?`1 ${one} per ${(x/y).toFixed(1)} ${many}`:`No ${one}s yet`;return [r(a,b,"conversation","dials"),r(b,c,"appointment","conversations"),r(c,h,"held appointment","booked")]}
function filled(d:Draft,key:StepKey){return key==="numbers"?COUNTS.every(k=>/^\d{1,6}$/.test(d[k.key])):!!d[key].trim()}
export default function ConsistencyPlanPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/consistency-plan-feedback",{dials:num(draft.dials),conversations:num(draft.conversations),booked:num(draft.booked),held:num(draft.held),inputs:draft.inputs,leak:draft.leak,habit:draft.habit,story:draft.story});const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);const numbersIn=filled(draft,"numbers");
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="activity-mindset")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="activity-mindset" itemId="consistency-plan"/><div className="eyebrow">Module 9 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Build your consistency plan.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>Start from last week&rsquo;s real numbers, then plan next week around what you control: your input goals, the one step you&rsquo;ll fix, how every call block starts, and an honest rewrite of the story you tell after a bad week. The coach checks it against the lessons and writes your Monday-morning start.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="numbers"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:16}}>{COUNTS.map(c=><label key={c.key}><span style={labelStyle}>{c.label}</span><input style={field} inputMode="numeric" maxLength={6} value={draft[c.key]} onChange={e=>update({[c.key]:e.target.value.replace(/\D/g,"")})} placeholder="0"/></label>)}</div>
:<textarea style={{...field,minHeight:160,resize:"vertical"}} maxLength={1500} value={draft[current.key]} onChange={e=>update({[current.key]:e.target.value})} placeholder={current.placeholder}/>}
{numbersIn&&(current.key==="numbers"||current.key==="leak")&&<div style={{marginTop:18,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>YOUR RATIOS</small><ul style={{margin:"6px 0 0",paddingLeft:18,lineHeight:1.7}}>{ratios(draft).map(r=><li key={r}>{r}</li>)}</ul></div>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/activity-mindset/lessons/bounce-back">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your plan…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="activity-mindset" itemId="consistency-plan"/></div></PreviewGate></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>MONDAY MORNING</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>{feedback.mondayStart}</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE FOR NEXT WEEK</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the plan as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my plan</button><button className="btn btn-primary" onClick={onSave}>Save my plan →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const numbers=`${draft.dials} dials, ${draft.conversations} conversations, ${draft.booked} booked, ${draft.held} held`;const ratioText=ratios(draft).join("\n");const saveStatus=useSaveExercise({type:"consistency-plan",moduleSlug:"activity-mindset",itemId:"consistency-plan",title:`Consistency plan: week of ${new Date().toLocaleDateString(undefined,{month:"short",day:"numeric"})}`,data:{numbers,ratios:ratioText,inputs:draft.inputs,leak:draft.leak,habit:draft.habit,story:draft.story,mondayStart:feedback.mondayStart,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadConsistencyPlanPdf({numbers,ratios:ratioText,inputs:draft.inputs,leak:draft.leak,habit:draft.habit,story:draft.story,mondayStart:feedback.mondayStart,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55,whiteSpace:"pre-line"}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>PLAN SAVED · NEXT WEEK</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{numbers}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("YOUR RATIOS",ratioText)}
{row("INPUT GOALS",draft.inputs)}
{row("THE LEAK AND THE FIX",draft.leak)}
{row("FIRST-DIAL HABIT",draft.habit)}
{row("THE STORY, REWRITTEN",draft.story)}
{row("MONDAY MORNING",<p style={{fontFamily:"Georgia,serif",fontSize:18,margin:0}}>{feedback.mondayStart}</p>)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE FOR NEXT WEEK</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Start a new plan</button></div><Link className="btn btn-primary" href="/quiz/activity-mindset">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
