"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadCallPlanPdf } from "@/lib/pdf";
// Module 2 exercise: the rep writes tomorrow's call plan in four steps, gets coach feedback on each part from /api/call-plan-feedback, then keeps the plan as a one-page PDF.
type Area="target"|"blocks"|"routine"|"logging";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;oneChange:string};
type Block={start:string;end:string;plan:string};
type Plan={leadCount:string;dailyTarget:string;targetReason:string;amBlock:Block;middayBlock:Block;pmBlock:Block;routine:string;logging:string};
const EMPTY:Plan={leadCount:"",dailyTarget:"",targetReason:"",amBlock:{start:"",end:"",plan:""},middayBlock:{start:"",end:"",plan:""},pmBlock:{start:"",end:"",plan:""},routine:"",logging:""};
const VERDICT={ready:{label:"Ready to run",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const AREA_TITLE:Record<Area,string>={target:"Daily target",blocks:"Call blocks",routine:"Pre-call routine",logging:"Logging"};
const STEPS:{area:Area;title:string;hint:string}[]=[
 {area:"target",title:"Set tomorrow's number.",hint:"Size it from your list, not your mood. Write it down before the first dial."},
 {area:"blocks",title:"Schedule your call blocks.",hint:"Give each block a time and one job. Nothing else happens inside a block."},
 {area:"routine",title:"Write your pre-call routine.",hint:"The exact steps you'll run before every block, one per line, ending with the first dial."},
 {area:"logging",title:"Decide what you'll log, and when.",hint:"Which numbers go in the CRM, and at what moment."},
];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
function filled(p:Plan,area:Area){const b=(x:Block)=>x.start.trim()&&x.end.trim()&&x.plan.trim();switch(area){case "target":return !!(p.leadCount.trim()&&p.dailyTarget.trim()&&p.targetReason.trim());case "blocks":return !!(b(p.amBlock)&&b(p.middayBlock)&&b(p.pmBlock));case "routine":return !!p.routine.trim();case "logging":return !!p.logging.trim()}}
export default function CallPlan(){const [step,setStep]=useState(0);const [plan,setPlan]=useState<Plan>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Plan>)=>{setPlan(p=>({...p,...patch}));setFeedback(null);setError("")};
const updateBlock=(key:"amBlock"|"middayBlock"|"pmBlock",patch:Partial<Block>)=>update({[key]:{...plan[key],...patch}} as Partial<Plan>);
async function getFeedback(){setLoading(true);setError("");try{const res=await fetch("/api/call-plan-feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(plan)});const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(plan,current.area);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editArea=(area:Area)=>{setStep(STEPS.findIndex(s=>s.area===area));setReviewing(false)};
const restart=()=>{setPlan(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="preparing-to-make-calls" itemId="call-plan"/><div className="eyebrow">Module 2 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Build your call plan.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>Plan tomorrow before tomorrow starts: the number, the blocks, the routine and the logging. The coach checks it against the lessons, and you keep a one-page plan for next to the phone.</p>
{done&&feedback?<Summary plan={plan} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editArea} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{AREA_TITLE[current.area].toUpperCase()}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.area==="target"&&<div style={{display:"grid",gap:18}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Leads on your list this week</span><input style={field} inputMode="numeric" value={plan.leadCount} onChange={e=>update({leadCount:e.target.value})} placeholder="e.g. 150"/></label><label><span style={labelStyle}>Daily dial target</span><input style={field} inputMode="numeric" value={plan.dailyTarget} onChange={e=>update({dailyTarget:e.target.value})} placeholder="e.g. 35"/></label></div><label><span style={labelStyle}>How did you get that number?</span><textarea style={{...field,minHeight:110,resize:"vertical"}} maxLength={1000} value={plan.targetReason} onChange={e=>update({targetReason:e.target.value})} placeholder="Show your math."/></label></div>}
{current.area==="blocks"&&<div style={{display:"grid",gap:22}}>{([["amBlock","AM block"],["middayBlock","Midday block"],["pmBlock","PM block"]] as const).map(([key,name])=><div key={key} style={{border:"1px solid var(--line)",borderRadius:12,padding:18}}><b style={{display:"block",marginBottom:12}}>{name}</b><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,marginBottom:12}}><label><span style={labelStyle}>Start</span><input type="time" style={field} value={plan[key].start} onChange={e=>updateBlock(key,{start:e.target.value})}/></label><label><span style={labelStyle}>End</span><input type="time" style={field} value={plan[key].end} onChange={e=>updateBlock(key,{end:e.target.value})}/></label></div><label><span style={labelStyle}>What this block is for</span><input style={field} maxLength={1000} value={plan[key].plan} onChange={e=>updateBlock(key,{plan:e.target.value})} placeholder="Which leads or calls you’ll work in this block"/></label></div>)}</div>}
{current.area==="routine"&&<textarea style={{...field,minHeight:170,resize:"vertical"}} maxLength={1000} value={plan.routine} onChange={e=>update({routine:e.target.value})} placeholder="One step per line"/>}
{current.area==="logging"&&<textarea style={{...field,minHeight:150,resize:"vertical"}} maxLength={1000} value={plan.logging} onChange={e=>update({logging:e.target.value})} placeholder="What you’ll track, and when you’ll enter it"/>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/preparing-to-make-calls/lessons/activity-vs-outcome">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your plan…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="preparing-to-make-calls" itemId="call-plan"/></div></AppShell>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(a:Area)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
{STEPS.map(({area})=>({area,...feedback.sections[area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{AREA_TITLE[sec.area]}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.area)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE TOMORROW</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the plan as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my plan</button><button className="btn btn-primary" onClick={onSave}>Save my plan →</button></div></section>}
function Summary({plan,feedback,onRestart}:{plan:Plan;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const blocks=[{label:"AM",...plan.amBlock},{label:"Midday",...plan.middayBlock},{label:"PM",...plan.pmBlock}];const saveStatus=useSaveExercise({type:"call-plan",moduleSlug:"preparing-to-make-calls",itemId:"call-plan",title:"Call plan",data:{leadCount:plan.leadCount,dailyTarget:plan.dailyTarget,targetReason:plan.targetReason,blocks,routine:plan.routine,logging:plan.logging,verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});const steps=plan.routine.split(/\n+/).map(l=>l.replace(/^\s*(\d+[.)]|[-*])\s*/,"").trim()).filter(Boolean);
const downloadPdf=()=>{setPdfError("");downloadCallPlanPdf({leadCount:plan.leadCount,dailyTarget:plan.dailyTarget,targetReason:plan.targetReason,blocks,routine:plan.routine,logging:plan.logging,coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,flexWrap:"wrap"}}><div><small style={{color:"var(--lime)",fontWeight:900}}>PLAN SAVED</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>Tomorrow&apos;s call plan</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Coach rating: {v.label}</span></div><div style={{textAlign:"right"}}><div style={{fontFamily:"Georgia,serif",fontSize:44,lineHeight:1}}>{plan.dailyTarget}</div><small style={{color:"#c9dbd5"}}>dials, from {plan.leadCount} leads</small></div></div><div style={{padding:"16px 36px 30px"}}>
{row("CALL BLOCKS",<div style={{display:"grid",gap:8}}>{blocks.map(b=><div key={b.label} style={{display:"grid",gridTemplateColumns:"80px 130px 1fr",gap:10}}><b style={{color:"var(--green)"}}>{b.label}</b><span>{b.start}–{b.end}</span><span>{b.plan}</span></div>)}</div>)}
{row("PRE-CALL ROUTINE (SAME EVERY TIME)",steps.length>1?<ol style={{margin:0,paddingLeft:22}}>{steps.map((s,i)=><li key={i}>{s}</li>)}</ol>:plan.routine)}
{row("WHAT I LOG, AND WHEN",plan.logging)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH: ONE CHANGE BEFORE TOMORROW</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Start a new plan</button></div><Link className="btn btn-primary" href="/quiz/preparing-to-make-calls">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
