"use client"; import Link from "next/link"; import { useState } from "react"; import { AppShell } from "@/components/AppShell"; import { authedPost } from "@/lib/authedFetch"; import { ModuleBreadcrumb, ModulePager } from "@/components/ModuleNav"; import { SavedNote, useSaveExercise } from "@/components/Tracking"; import { downloadCallLabPdf } from "@/lib/pdf"; import { PreviewGate } from "@/components/PreviewGate"; import { modules } from "@/data/curriculum";
// Module 11 exercise: for one real business, the rep writes their own call lab: the setup, the opening, the hard moment they expect and their answer, and the ask. Coach feedback (a score on the five moves from the labs, plus one curveball to practice) comes from /api/call-lab-feedback, then the lab can be kept as a PDF.
type StepKey="merchant"|"setup"|"opening"|"objection"|"ask";
type Area=Exclude<StepKey,"merchant">;
type Move="intro"|"question"|"steady"|"number"|"time";
type Section={status:"good"|"fix";feedback:string;suggestion:string};
type Feedback={verdict:"ready"|"almost"|"needs_work";summary:string;sections:Record<Area,Section>;moves:Record<Move,boolean>;curveball:string;curveballAnswer:string;oneChange:string};
type Draft={vertical:string;merchant:string;answerer:string;setup:string;opening:string;objection:string;ask:string};
const EMPTY:Draft={vertical:"",merchant:"",answerer:"",setup:"",opening:"",objection:"",ask:""};
const VERTICALS=["Restaurant","Retail","Service business (salon, auto, contractor)","Medical or dental office","E-commerce","Other"];
const VERDICT={ready:{label:"Ready to call",bg:"var(--green)",fg:"white",pdf:"strong" as const},almost:{label:"Almost there",bg:"var(--lime)",fg:"var(--ink)",pdf:"close" as const},needs_work:{label:"Needs work",bg:"#f3d9c9",fg:"#7a2e0e",pdf:"needs_work" as const}};
const STEPS:{key:StepKey;kicker:string;title:string;hint:string;placeholder:string}[]=[
 {key:"merchant",kicker:"THE BUSINESS",title:"Pick a real business from your list.",hint:"Choose a vertical you don’t call every day, if you can. Practicing across different businesses makes you better at all of them.",placeholder:""},
 {key:"setup",kicker:"THE SETUP",title:"When will you call, and why them?",hint:"The time that fits how this business runs its day, the problem it most likely has, and your reason for calling that’s about this business specifically.",placeholder:"e.g. Call at 2:30 p.m., after lunch. Restaurants usually care about tips, rush-hour speed and delivery-app costs. Their website shows they opened a second location in March, so my reason is helping owners with two locations see what they pay per order."},
 {key:"opening",kicker:"THE OPENING",title:"What will you say to whoever answers, then the owner?",hint:"To the person who answers: who you are, why you’re calling, and a request for help. To the owner: your reason, then one easy question about their business.",placeholder:"e.g. Host: “Hi, this is Alex with BytePOS. I help restaurants around here with what they pay to take cards. Who usually handles that?” Owner: “Hi Maria, Alex with BytePOS. I saw you opened the second location this spring. Did you keep the same processor for both?”"},
 {key:"objection",kicker:"THE HARD MOMENT",title:"What’s the hardest thing they’re likely to say, and your answer?",hint:"“Not interested,” “we’re happy,” “send me information” or “what’s your rate?” Write the objection and exactly what you’ll say back.",placeholder:"e.g. “We’re happy with who we have.” → “Good, that’s what you want from a processor. Out of curiosity, when did someone last walk you through the statement for both locations?”"},
 {key:"ask",kicker:"THE ASK",title:"How will you ask for the meeting?",hint:"One number in their terms, a small next step instead of a switch, and a specific day and time that fits their business.",placeholder:"e.g. “Between the two locations that’s a lot of $25 tickets. Send me last month’s statements and I’ll show you what you’re really paying per ticket. If it’s fair, I’ll tell you. Could we take fifteen minutes Wednesday at 3, before dinner prep?”"},
];
const AREAS:{area:Area;title:string;step:number}[]=[{area:"setup",title:"The setup",step:1},{area:"opening",title:"The opening",step:2},{area:"objection",title:"The hard moment",step:3},{area:"ask",title:"The ask",step:4}];
const MOVES:{move:Move;label:string}[]=[{move:"intro",label:"Who you are and why you’re calling"},{move:"question",label:"A question about their business"},{move:"steady",label:"Steady through the first no"},{move:"number",label:"One number in their terms"},{move:"time",label:"A specific day and time"}];
const RED="#a3320b";
const field={width:"100%",border:"1px solid var(--line)",borderRadius:12,padding:"13px 15px",background:"#fbfcf9",lineHeight:1.5} as const;
const labelStyle={display:"block",fontSize:13,fontWeight:800,margin:"0 0 7px"} as const;
const unquote=(t:string)=>t.trim().replace(/^["“]+|["”]+$/g,"");
const movesHit=(m:Record<Move,boolean>)=>MOVES.filter(x=>m[x.move]).length;
function filled(d:Draft,key:StepKey){return key==="merchant"?!!(d.vertical&&d.merchant.trim()&&d.answerer.trim()):!!d[key].trim()}
export default function CallLabPractice(){const [step,setStep]=useState(0);const [draft,setDraft]=useState<Draft>(EMPTY);const [feedback,setFeedback]=useState<Feedback|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reviewing,setReviewing]=useState(false);const [done,setDone]=useState(false);
const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setFeedback(null);setError("")};
async function getFeedback(){setLoading(true);setError("");try{const res=await authedPost("/api/call-lab-feedback",draft);const data=await res.json();if(!res.ok)throw new Error(data.error||"AI feedback failed. Try again.");setFeedback(data.feedback);setReviewing(true);window.scrollTo(0,0)}catch(e){setError(e instanceof Error?e.message:"AI feedback failed. Try again.")}finally{setLoading(false)}}
const current=STEPS[step];const canAdvance=filled(draft,current.key);
const onPrimary=()=>{if(step<STEPS.length-1){setStep(step+1);return}if(feedback){setReviewing(true);return}void getFeedback()};
const editStep=(s:number)=>{setStep(s);setReviewing(false)};
const restart=()=>{setDraft(EMPTY);setFeedback(null);setError("");setStep(0);setReviewing(false);setDone(false)};
return <AppShell active="Practice"><PreviewGate status={modules.find(m=>m.slug==="vertical-practice")!.status}><div style={{padding:"46px 4vw 70px",maxWidth:950,margin:"auto"}}><ModuleBreadcrumb moduleSlug="vertical-practice" itemId="call-lab"/><div className="eyebrow">Module 11 practice · 10 minutes</div><h1 className="display" style={{fontSize:40,margin:"14px 0 10px"}}>Build your own call lab.</h1><p style={{color:"var(--muted)",fontSize:17,lineHeight:1.6,maxWidth:720}}>Pick one real business on your list and write the lab for it, the way the four labs in this module were written: the setup, the opening, the hardest moment you expect, and how you&rsquo;ll ask for the meeting. The coach scores it against the five moves and throws you one curveball to practice.</p>
{done&&feedback?<Summary draft={draft} feedback={feedback} onRestart={restart}/>:reviewing&&feedback?<Review feedback={feedback} onEdit={editStep} onBack={()=>setReviewing(false)} onSave={()=>{setDone(true);window.scrollTo(0,0)}}/>:<div className="card" style={{marginTop:32,overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white",display:"flex",justifyContent:"space-between",gap:16}}><div><small style={{color:"var(--lime)",fontWeight:900}}>{current.kicker}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 0"}}>{current.title}</h2></div><span style={{fontSize:13,color:"#c9dbd5",whiteSpace:"nowrap"}}>Step {step+1} of {STEPS.length}</span></div><div style={{padding:36}}><p style={{color:"var(--muted)",marginTop:0,lineHeight:1.55}}>{current.hint}</p>
{current.key==="merchant"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}><label><span style={labelStyle}>Vertical</span><select style={field} value={draft.vertical} onChange={e=>update({vertical:e.target.value})}><option value="">Choose one…</option>{VERTICALS.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span style={labelStyle}>Business</span><input style={field} maxLength={1500} value={draft.merchant} onChange={e=>update({merchant:e.target.value})} placeholder="e.g. Casa Verde, family restaurant"/></label><label><span style={labelStyle}>Who usually answers</span><input style={field} maxLength={1500} value={draft.answerer} onChange={e=>update({answerer:e.target.value})} placeholder="e.g. The host, or the owner directly"/></label></div>
:<textarea style={{...field,minHeight:160,resize:"vertical"}} maxLength={1500} value={draft[current.key]} onChange={e=>update({[current.key]:e.target.value})} placeholder={current.placeholder}/>}
{error&&<p role="alert" style={{color:RED,fontSize:14,margin:"14px 0 0"}}>{error}</p>}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:26}}>{step===0?<Link className="btn btn-outline" href="/courses/vertical-practice/lessons/ecommerce-lab">← Back to lesson</Link>:<button className="btn btn-outline" onClick={()=>setStep(step-1)}>← Back</button>}<div style={{display:"flex",gap:7}}>{STEPS.map((_,i)=><span key={i} style={{width:i===step?24:8,height:8,borderRadius:9,background:i===step?"var(--green)":"#dce2db"}}/>)}</div><button className="btn btn-primary" disabled={!canAdvance||loading} onClick={onPrimary}>{step<STEPS.length-1?"Continue →":feedback?"Back to feedback →":loading?"Checking your lab…":"Get coach feedback →"}</button></div></div></div>}<ModulePager moduleSlug="vertical-practice" itemId="call-lab"/></div></PreviewGate></AppShell>}
function MoveList({moves}:{moves:Record<Move,boolean>}){return <div style={{display:"grid",gap:8,marginTop:10}}>{MOVES.map(m=><div key={m.move} style={{display:"flex",alignItems:"center",gap:10,fontSize:15}}><span style={{width:22,height:22,flex:"none",borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:moves[m.move]?"var(--green)":RED}}>{moves[m.move]?"✓":"!"}</span>{m.label}</div>)}</div>}
function Review({feedback,onEdit,onBack,onSave}:{feedback:Feedback;onEdit:(step:number)=>void;onBack:()=>void;onSave:()=>void}){const v=VERDICT[feedback.verdict];return <section aria-live="polite" className="card" style={{marginTop:32,padding:"30px 34px"}}><div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>COACH FEEDBACK</small><span style={{background:v.bg,color:v.fg,fontSize:12,fontWeight:900,padding:"4px 10px",borderRadius:20}}>{v.label}</span></div><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"14px 0 6px"}}>{feedback.summary}</p>
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>THE FIVE MOVES · {movesHit(feedback.moves)} OF 5</small><MoveList moves={feedback.moves}/></div>
{AREAS.map(a=>({...a,...feedback.sections[a.area]})).map(sec=><div key={sec.area} style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:22,height:22,borderRadius:"50%",display:"grid",placeItems:"center",fontSize:12,fontWeight:900,color:"white",background:sec.status==="good"?"var(--green)":RED}}>{sec.status==="good"?"✓":"!"}</span><b>{sec.title}</b></div><button className="btn btn-outline" style={{fontSize:12,minHeight:36,padding:"0 14px"}} onClick={()=>onEdit(sec.step)}>Edit this part</button></div><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}>{sec.feedback}</p>{sec.status==="fix"&&sec.suggestion.trim()&&<div style={{marginTop:12,background:"#f7f9f2",border:"1px solid var(--line)",borderRadius:10,padding:"12px 16px"}}><small style={{fontWeight:900,letterSpacing:".1em",color:"var(--muted)"}}>TRY THIS</small><p style={{margin:"6px 0 0",lineHeight:1.55,whiteSpace:"pre-line"}}>{sec.suggestion}</p></div>}</div>)}
<div style={{padding:"18px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>CURVEBALL TO PRACTICE</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.5,margin:"8px 0 0"}}>&ldquo;{unquote(feedback.curveball)}&rdquo;</p><p style={{margin:"10px 0 0",lineHeight:1.6,color:"var(--muted)"}}><b style={{color:"var(--ink)"}}>You could say:</b> &ldquo;{unquote(feedback.curveballAnswer)}&rdquo;</p></div>
<div style={{marginTop:6,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"18px 22px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>ONE CHANGE BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div>
<p style={{fontSize:13,color:"var(--muted)",margin:"18px 0 0"}}>Edit any part to get fresh feedback, or save the lab as it is.</p><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginTop:14}}><button className="btn btn-outline" onClick={onBack}>← Back to my lab</button><button className="btn btn-primary" onClick={onSave}>Save my lab →</button></div></section>}
function Summary({draft,feedback,onRestart}:{draft:Draft;feedback:Feedback;onRestart:()=>void}){const v=VERDICT[feedback.verdict];const [pdfError,setPdfError]=useState("");const hit=movesHit(feedback.moves);const missed=MOVES.filter(m=>!feedback.moves[m.move]).map(m=>m.label);
const saveStatus=useSaveExercise({type:"call-lab",moduleSlug:"vertical-practice",itemId:"call-lab",title:`Call lab: ${draft.merchant}`,data:{vertical:draft.vertical,merchant:draft.merchant,answerer:draft.answerer,setup:draft.setup,opening:draft.opening,objection:draft.objection,ask:draft.ask,movesHit:hit,movesMissed:missed.join(", "),curveball:unquote(feedback.curveball),curveballAnswer:unquote(feedback.curveballAnswer),verdict:feedback.verdict,verdictLabel:v.label,oneChange:feedback.oneChange}});
const downloadPdf=()=>{setPdfError("");downloadCallLabPdf({vertical:draft.vertical,merchant:draft.merchant,answerer:draft.answerer,setup:draft.setup,opening:draft.opening,objection:draft.objection,ask:draft.ask,moves:MOVES.map(m=>({label:m.label,hit:feedback.moves[m.move]})),curveball:unquote(feedback.curveball),curveballAnswer:unquote(feedback.curveballAnswer),coachVerdict:v.pdf,coachVerdictLabel:v.label,oneChange:feedback.oneChange,date:new Date()}).catch(()=>setPdfError("Couldn’t create the PDF. Try again."))};
const row=(label:string,body:React.ReactNode)=><div style={{padding:"20px 0",borderTop:"1px solid var(--line)"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--muted)"}}>{label}</small><div style={{marginTop:8,fontSize:16,lineHeight:1.55,whiteSpace:"pre-line"}}>{body}</div></div>;
return <div style={{marginTop:32}}><div className="card" style={{overflow:"hidden"}}><div style={{background:"var(--green)",padding:28,color:"white"}}><small style={{color:"var(--lime)",fontWeight:900}}>LAB SAVED · {draft.vertical.toUpperCase()}</small><h2 style={{fontFamily:"Georgia,serif",fontSize:27,margin:"8px 0 4px"}}>{draft.merchant}</h2><span style={{fontSize:13,color:"#c9dbd5"}}>Who answers: {draft.answerer} · Five moves: {hit} of 5 · Coach rating: {v.label}</span></div><div style={{padding:"16px 36px 30px"}}>
{row("THE SETUP",draft.setup)}
{row("THE OPENING",draft.opening)}
{row("THE HARD MOMENT",draft.objection)}
{row("THE ASK",draft.ask)}
{row(`THE FIVE MOVES · ${hit} OF 5`,<MoveList moves={feedback.moves}/>)}
{row("CURVEBALL TO PRACTICE",<><p style={{fontFamily:"Georgia,serif",fontSize:18,margin:0}}>&ldquo;{unquote(feedback.curveball)}&rdquo;</p><p style={{margin:"8px 0 0",color:"var(--muted)"}}>You could say: &ldquo;{unquote(feedback.curveballAnswer)}&rdquo;</p></>)}
<div style={{marginTop:10,background:"#f2f6e7",borderLeft:"5px solid var(--lime)",padding:"20px 24px"}}><small style={{fontWeight:900,letterSpacing:".12em",color:"var(--green)"}}>BEFORE YOU CALL</small><p style={{fontFamily:"Georgia,serif",fontSize:20,lineHeight:1.45,margin:"8px 0 0"}}>{feedback.oneChange}</p></div></div></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"space-between",alignItems:"center",marginTop:24}}><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className="btn btn-outline" onClick={downloadPdf}>Download PDF</button><button className="btn btn-outline" onClick={onRestart}>Build another lab</button></div><Link className="btn btn-primary" href="/quiz/vertical-practice">Continue to Knowledge Check →</Link></div><SavedNote status={saveStatus}/>{pdfError&&<p role="alert" style={{color:RED,fontSize:14,marginTop:14}}>{pdfError}</p>}</div>}
